using System.Text.Json;
using ActionExamples.ViewAnnotations;
using Calendar.Domain;
using DisplayPresentation.Domain;
using DisplayPresentation.UseCases;

internal static class ProducerInteropTests
{
    internal static void WriteFixtures(string path)
    {
        var start = DateTimeOffset.Parse("2026-09-06T10:00:00Z");
        var fixtures = new Dictionary<string, PresentationInput>();
        foreach (var count in new[] { 0, 1, 7, 100 })
        {
            var output = CalendarA2UiPresentations.Create(Enumerable.Range(0, count).Select(i => CalendarEvent.Create(
                $"event-{i}", $"Event {i}", start.AddHours(i), start.AddHours(i + 1), $"Note {i}", "Room")).ToArray());
            fixtures[$"calendar{count}"] = new(output.Template, output.Document);
        }
        var reminder = CalendarA2UiPresentations.CreateReminder(CalendarReminder.Create("r1", "Follow up", start, "Bring notes").WithState("Blocked"));
        fixtures["reminder"] = new(reminder.Template, reminder.Document);
        File.WriteAllText(path, "// Generated by DisplayPresentation.UseCases.Tests --write-fixtures; do not edit.\nwindow.presentationFixtures = " +
            JsonSerializer.Serialize(fixtures) + ";\n");
    }

    internal static void Run()
    {
        var parser = new A2UiPresentationParser();
        var start = DateTimeOffset.Parse("2026-09-06T10:00:00Z");
        foreach (var count in new[] { 0, 1, 2, 7, 100 })
        {
            var events = Enumerable.Range(0, count).Select(i => CalendarEvent.Create(
                $"event-{i}", $"Event {i}", start.AddHours(i), start.AddHours(i + 1), $"Note {i}", "Room")).ToArray();
            var output = CalendarA2UiPresentations.Create(events);
            var outcome = parser.Parse(new(output.Template, output.Document));
            Check(outcome.IsSuccess, $"Calendar {count} events must parse: {outcome.Failure}");
            var values = Texts(outcome.Plan!.Surface.Root).ToArray();
            Check(values.Length == count * 4, "Every event field must survive parsing.");
            Check(values.Where((_, index) => index % 4 == 0).Select(x => x.Value)
                .SequenceEqual(events.Select(x => x.Title)), "Event order must be preserved.");
            var roundTrip = parser.Parse(A2UiPresentationSerializer.Serialize(outcome.Plan.Surface));
            Check(roundTrip.IsSuccess && Texts(roundTrip.Plan!.Surface.Root).SequenceEqual(values),
                "Reconstructed snapshots must preserve semantic values and order.");
        }

        var reminder = CalendarA2UiPresentations.CreateReminder(
            CalendarReminder.Create("r1", "Follow up", start, "Bring notes").WithState("Blocked"));
        Check(parser.Parse(new(reminder.Template, reminder.Document)).IsSuccess, "Calendar Reminder must render.");
        var oversized = CalendarA2UiPresentations.Create(Enumerable.Range(0, 100).Select(i => CalendarEvent.Create(
            $"large-{i}", "Long note", start, start.AddHours(1), new string('x', 4096), "Room")).ToArray());
        Check(!oversized.FitsTransport && !parser.Parse(new(oversized.Template, oversized.Document)).IsSuccess,
            "Producer and renderer must agree on the transport limit even for a permitted event count.");
        var info = JsonSerializer.Serialize(new { TizenEntity = new { Id = "page1", Extra = JsonSerializer.Serialize(
            new { schemaVersion = 1, page = new { surface = "Search" }, draft = new { text = "Unsaved" } }) } });
        Check(ViewSnapshotPresentation.TryCreate("Tizen.Entity", "page1", info, out var template, out var document),
            "The shared current-state builder must produce a page presentation.");
        Check(parser.Parse(new(template, document)).IsSuccess, "Shared page/control output must render.");
        Console.WriteLine("ProducerInteropTests: PASS (Calendar 0/1/2/7/100, Reminder, shared page/control)");
    }

    internal static IEnumerable<TextValue> Texts(SemanticNode node) => node switch
    {
        TextValue text => [text],
        VerticalGroup group => group.Children.SelectMany(Texts),
        _ => throw new InvalidOperationException("Unexpected semantic node."),
    };

    private static void Check(bool condition, string message)
    {
        if (!condition) throw new InvalidOperationException(message);
    }
}
