<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../../Shared/ViewAnnotations/NuiViewAnnotations.cs" Link="NuiViewAnnotations.cs" />
    <Content Include="../../actions/*.action;../../entities/*.entity" Link="res/%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
    <PackageReference Include="Tizen.NET" Version="14.0.0.19326" />
    <ProjectReference Include="../Calendar.Domain/Calendar.Domain.csproj" />
    <ProjectReference Include="../Calendar.Persistence/Calendar.Persistence.csproj" />
    <ProjectReference Include="../Calendar.UseCases/Calendar.UseCases.csproj" />
    <ProjectReference Include="../Calendar.ActionProvider/Calendar.ActionProvider.csproj" />
    <ProjectReference Include="../Calendar.ScheduleActionProvider/Calendar.ScheduleActionProvider.csproj" />
    <ProjectReference Include="../Calendar.ViewActionProvider/Calendar.ViewActionProvider.csproj" />
  </ItemGroup>
</Project>
