<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Browser.UseCases/Browser.UseCases.csproj" />
    <ProjectReference Include="../../../DisplayPresentation/src/DisplayPresentation.UseCases/DisplayPresentation.UseCases.csproj" />
  </ItemGroup>
</Project>
