<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <NoWarn>CS0108</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Tizen.NET" Version="13.0.0.19198" />
    <ProjectReference Include="../Reminder.Domain/Reminder.Domain.csproj" />
    <ProjectReference Include="../Reminder.ScheduleActionProvider/Reminder.ScheduleActionProvider.csproj" />
  </ItemGroup>
</Project>
