/**
 * Generated by tidlc 2.9.1.
 */

#pragma once

#include <bundle.h>
#include <rpc-port-parcel.h>
#include <rpc-port.h>
#include <glib.h>

#include <atomic>
#include <exception>
#include <functional>
#include <list>
#include <map>
#include <memory>
#include <mutex>
#include <set>
#include <string>
#include <vector>
#include <unordered_map>
#include <unordered_set>
#include <queue>

namespace rpc_port {
namespace calendar_action_provider {

class RawFdWrapper {
 public:
  RawFdWrapper() : fd_(-1) {}
  RawFdWrapper(int fd) : fd_(fd) {}

  int Get() const { return fd_; }
  void Set(int fd) { fd_ = fd; }

 private:
  int fd_;
};

class LocalExecution {
 public:
  class IEvent {
   public:
    virtual ~IEvent() = default;
    virtual void OnLocalConnected(void* context, const std::string& sender, const std::string& instance, bool sync) = 0;
    virtual void OnLocalDisconnected(void* context, const std::string& sender, const std::string& instance) = 0;
    virtual void OnLocalReceived(void* context, rpc_port_parcel_h parcel) = 0;
  };

  LocalExecution(std::string port_name, IEvent* listener);
  virtual ~LocalExecution() = default;

  void Connect(void* context, bool sync);
  void Disconnect(void* context);
  void SendResult(void* context, rpc_port_parcel_h parcel);
  void InvokeCallback(void* context, rpc_port_parcel_h parcel);

  void OnConnected(void* context, const std::string& sender, const std::string& instance, bool sync);
  void OnDisconnected(void* context, const std::string& sender, const std::string& instance);
  void OnReceived(void* context, rpc_port_parcel_h parcel);

  void SetListening(bool listening);
  bool IsListening() const;

  bool LoadSymbols();
  GMainContext* GetContext() const;

 private:
  using ProxyConnectFunc = int (*)(void*, bool);
  using ProxyDisconnectFunc = int (*)(void*);
  using ProxySendResultFunc = int (*)(void*, rpc_port_parcel_h);
  using ProxyInvokeCallbackFunc = int (*)(void*, rpc_port_parcel_h);

 private:
  std::string port_name_;
  IEvent* listener_;
  bool listening_ = false;
  bool loaded_ = false;
  ProxyConnectFunc connect_func_ = nullptr;
  ProxyDisconnectFunc disconnect_func_ = nullptr;
  ProxySendResultFunc send_result_func_ = nullptr;
  ProxyInvokeCallbackFunc invoke_callback_func_ = nullptr;
  std::unique_ptr<GMainContext, decltype(g_main_context_unref)*> context_;
};

class Bundle final {
 public:
  Bundle();
  explicit Bundle(bundle* handle, bool copy = true, bool own = true);
  Bundle(std::string raw);
  ~Bundle();

  Bundle(const Bundle& b);
  Bundle& operator = (const Bundle& b);
  Bundle(Bundle&& b) noexcept;
  Bundle& operator = (Bundle&&) noexcept;

  bundle* GetHandle() const;
  bundle* Detach();

 private:
  bundle* handle_;
  bool own_ = true;
};

class File final {
 public:
  File(std::string filename = "");

  const std::string& GetFileName() const;
  int Share(rpc_port_h port);

 private:
  std::string filename_;
};

class TizenEntity {
 public:

  TizenEntity();
  TizenEntity(std::string Id, std::string Extra);

  const std::string& GetId() const;
  void SetId(std::string Id);

  const std::string& GetExtra() const;
  void SetExtra(std::string Extra);

  std::string ToJson() const;
 private:
  std::string Id_;
  std::string Extra_;

};

class TizenEntityCalendar : public TizenEntity {
 public:

  TizenEntityCalendar();
  TizenEntityCalendar(std::string Id, std::string Extra, std::string Title, std::string StartDate, std::string EndDate, std::string Note, std::string Location);

  const std::string& GetTitle() const;
  void SetTitle(std::string Title);

  const std::string& GetStartDate() const;
  void SetStartDate(std::string StartDate);

  const std::string& GetEndDate() const;
  void SetEndDate(std::string EndDate);

  const std::string& GetNote() const;
  void SetNote(std::string Note);

  const std::string& GetLocation() const;
  void SetLocation(std::string Location);

  std::string ToJson() const;
 private:
  std::string Title_;
  std::string StartDate_;
  std::string EndDate_;
  std::string Note_;
  std::string Location_;

};

class TizenEntityQuery : public TizenEntity {
 public:

  TizenEntityQuery();
  TizenEntityQuery(std::string Id, std::string Extra, std::string Keyword, std::string Category, int Number);

  const std::string& GetKeyword() const;
  void SetKeyword(std::string Keyword);

  const std::string& GetCategory() const;
  void SetCategory(std::string Category);

  int GetNumber() const;
  void SetNumber(int Number);

  std::string ToJson() const;
 private:
  std::string Keyword_;
  std::string Category_;
  int Number_;

};

class TizenEntityCalendarSearchQuery : public TizenEntityQuery {
 public:

  TizenEntityCalendarSearchQuery();
  TizenEntityCalendarSearchQuery(std::string Id, std::string Extra, std::string Keyword, std::string Category, int Number, std::string StartDate, std::string EndDate, bool SearchTitle, bool SearchLocation, bool SearchNote);

  const std::string& GetStartDate() const;
  void SetStartDate(std::string StartDate);

  const std::string& GetEndDate() const;
  void SetEndDate(std::string EndDate);

  bool GetSearchTitle() const;
  void SetSearchTitle(bool SearchTitle);

  bool GetSearchLocation() const;
  void SetSearchLocation(bool SearchLocation);

  bool GetSearchNote() const;
  void SetSearchNote(bool SearchNote);

  std::string ToJson() const;
 private:
  std::string StartDate_;
  std::string EndDate_;
  bool SearchTitle_;
  bool SearchLocation_;
  bool SearchNote_;

};

class TizenEntityPresentation {
 public:

  TizenEntityPresentation();
  TizenEntityPresentation(std::string Document, std::string Template);

  const std::string& GetDocument() const;
  void SetDocument(std::string Document);

  const std::string& GetTemplate() const;
  void SetTemplate(std::string Template);

  std::string ToJson() const;
 private:
  std::string Document_;
  std::string Template_;

};

class TizenEntityStatus {
 public:

  TizenEntityStatus();
  TizenEntityStatus(bool Success, std::string Reason);

  bool GetSuccess() const;
  void SetSuccess(bool Success);

  const std::string& GetReason() const;
  void SetReason(std::string Reason);

  std::string ToJson() const;
 private:
  bool Success_;
  std::string Reason_;

};

namespace stub {

class UnitMap;

class Exception : public std::exception {
 public:
  virtual const char* what() const noexcept override {
    return "RPC Port Exception";
  }
};
class NotConnectedSocketException : public Exception {
 public:
  const char* what() const noexcept override {
    return "Not connected socket";
  }
};
class InvalidProtocolException : public Exception {
 public:
  const char* what() const noexcept override {
    return "Invalid protocol";
  }
};
class InvalidIOException : public Exception {
 public:
  const char* what() const noexcept override {
    return "Invalid I/O";
  }
};
class PermissionDeniedException : public Exception {
 public:
  const char* what() const noexcept override {
    return "Permission denied";
  }
};
class InvalidIDException : public Exception {
 public:
  const char* what() const noexcept override {
    return "Invalid ID";
  }
};
class InvalidArgumentException : public Exception {
 public:
  const char* what() const noexcept override {
    return "Invalid argument";
  }
};

class RemoteException : public Exception {
 public:
  RemoteException();
  RemoteException(std::string message);
  RemoteException(int cause, std::string message);

  int GetCause() const;
  const std::string& GetMessage() const;

 private:
  int cause_ = 0;
  std::string message_;
};

class TizenActionCalendar : public LocalExecution::IEvent {
 public:

  class ServiceBase;

  class CallbackBase {
   public:
    CallbackBase(int delegate_id, bool once);
    CallbackBase() = default;
    virtual ~CallbackBase() = default;

    int GetId() const;
    void SetId(int id);
    int GetSeqId() const;
    void SetSeqId(int seq_id);
    bool IsOnce() const;
    void SetOnce(bool once);

    std::string GetTag() const;

    void SetContext(void* context);
    void* GetContext() const;

   private:
    static std::atomic<int> seq_num_;
    int id_ = 0;
    int seq_id_ = 0;
    bool once_ = false;
    void* context_ = nullptr;
  };

  class ServiceBase : public std::enable_shared_from_this<ServiceBase> {
   public:
    class Factory {
     public:
      virtual ~Factory() = default;

      /// <summary>
      /// The method for making service instances
      /// </summary>
      /// <param name="sender">The client app ID</param>
      /// <param name="instance">The client instance ID</param>
      virtual std::unique_ptr<ServiceBase> CreateService(std::string sender, std::string instance) = 0;
    };

    virtual ~ServiceBase() = default;

    /// <summary>
    /// Gets client app ID
    /// </summary>
    const std::string& GetSender() const {
      return sender_;
    }

    /// <summary>
    /// Gets client instance ID
    /// </summary>
    const std::string& GetInstance() const {
      return instance_;
    }

    /// <summary>
    /// Sets the client app port
    /// </summary>
    /// <param name="port">The port of the client</param>
    void SetPort(rpc_port_h port);

    /// <summary>
    /// Disconnects from the client app
    /// </summary>
    /// <exception cref="InvalidIOException">
    /// Thrown when internal I/O error happen.
    /// </exception>
    void Disconnect();

    /// <summary>
    /// This method will be called when the client is connected
    /// </summary>
    virtual void OnCreate() = 0;

    /// <summary>
    /// This method will be called when the client is disconnected
    /// </summary>
    virtual void OnTerminate() = 0;

    void SetContext(void* context);
    void* GetContext() const;
    void SetParent(const TizenActionCalendar* parent);
    int Dispatch(rpc_port_h port, rpc_port_h callback_port, rpc_port_parcel_h parcel, std::shared_ptr<ServiceBase> service);
    int Dispatch(rpc_port_h port, rpc_port_h callback_port, rpc_port_parcel_h parcel);

    virtual TizenEntityStatus AddEvent(TizenEntityCalendar calendar) = 0;
    virtual TizenEntityStatus RemoveEvent(TizenEntityCalendar calendar) = 0;
    virtual TizenEntityStatus Search(TizenEntityQuery query, std::vector<TizenEntityCalendar>& result) = 0;
    virtual TizenEntityStatus ToPresentation(TizenEntityCalendar calendar, TizenEntityPresentation& result) = 0;
    virtual TizenEntityStatus UpdateEvent(TizenEntityCalendar calendar) = 0;
    virtual TizenEntityStatus GetEventByIds(std::vector<std::string> ids, std::vector<TizenEntityCalendar>& result, std::vector<std::string>& unresolvedIds) = 0;
    virtual TizenEntityStatus SearchInPeriod(TizenEntityCalendarSearchQuery calendarSearchQuery, std::vector<TizenEntityCalendar>& result) = 0;

   protected:
    ServiceBase(std::string sender, std::string instance);

   private:
    using DispatchFunc = std::function<void(rpc_port_h, rpc_port_h, int, const UnitMap&)>;

    void SetPrivilegeMap();
    bool CheckPrivileges(rpc_port_h port, int method_id);
    void DispatchAddEvent(rpc_port_h port, rpc_port_h callback_port, int seq_num, const UnitMap& unit_map);
    void DispatchRemoveEvent(rpc_port_h port, rpc_port_h callback_port, int seq_num, const UnitMap& unit_map);
    void DispatchSearch(rpc_port_h port, rpc_port_h callback_port, int seq_num, const UnitMap& unit_map);
    void DispatchToPresentation(rpc_port_h port, rpc_port_h callback_port, int seq_num, const UnitMap& unit_map);
    void DispatchUpdateEvent(rpc_port_h port, rpc_port_h callback_port, int seq_num, const UnitMap& unit_map);
    void DispatchGetEventByIds(rpc_port_h port, rpc_port_h callback_port, int seq_num, const UnitMap& unit_map);
    void DispatchSearchInPeriod(rpc_port_h port, rpc_port_h callback_port, int seq_num, const UnitMap& unit_map);

   private:
    std::string sender_;
    std::string instance_;
    rpc_port_h port_ = nullptr;
    std::unordered_map<int, DispatchFunc> dispatch_funcs_;
    std::unordered_map<int, std::vector<std::string>> privilege_map_;
    void* context_ = nullptr;
    const TizenActionCalendar* parent_ = nullptr;
  };

  TizenActionCalendar();
  ~TizenActionCalendar();

  /// <summary>
  /// Listens to client apps
  /// </summary>
  /// <param name="service_factory">The factory object for making service instances</param>
  /// <exception cref="InvalidIOException">
  /// Thrown when internal I/O error happen.
  /// </exception>
  void Listen(std::shared_ptr<ServiceBase::Factory> service_factory);
  /// <summary>
  /// Gets service objects which are connected
  /// </summary>
  /// <returns>The list of service objects which are connected</returns>
  const std::list<std::shared_ptr<ServiceBase>>& GetServices() const {
    return services_;
  }

  rpc_port_stub_h GetRaw() const {
    return stub_;
  }

 private:
  enum class MethodId : int {
    __Result = 0,
    __Callback = 1,
    AddEvent = 2,
    RemoveEvent = 3,
    Search = 4,
    ToPresentation = 5,
    UpdateEvent = 6,
    GetEventByIds = 7,
    SearchInPeriod = 8,
  };

  static void OnConnectedCb(const char* sender, const char* instance, void* user_data);
  static void OnDisconnectedCb(const char* sender, const char* instance, void* user_data);
  static int OnReceivedCb(const char* sender, const char* instance, rpc_port_h port, void* user_data);

  void OnLocalConnected(void* context, const std::string& sender, const std::string& instance, bool sync) override;
  void OnLocalDisconnected(void* context, const std::string& sender, const std::string& instance) override;
  void OnLocalReceived(void* context, rpc_port_parcel_h parcel) override;

 private:
  rpc_port_stub_h stub_ = nullptr;
  std::shared_ptr<ServiceBase::Factory> service_factory_;
  std::list<std::shared_ptr<ServiceBase>> services_;
};

}  // namespace stub
}  // namespace calendar_action_provider
}  // namespace rpc_port

