/**
 * Generated by tidlc 2.9.1.
 */

#pragma GCC diagnostic ignored "-Wmaybe-uninitialized"

#include "schedule_action_provider.h"

#include <assert.h>
#include <dlog.h>
#include <stdlib.h>

#include <app_common.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <libgen.h>
#include <glib.h>
#include <dlog.h>
#include <dlfcn.h>
#include <rpc-port.h>
#include <rpc-port-parcel.h>
#include <unistd.h>

#include <map>
#include <memory>
#include <set>
#include <string>
#include <stdexcept>
#include <utility>
#include <unordered_map>

#undef LOG_TAG
#define LOG_TAG "RPC_PORT_STUB"

#undef _E
#define _E(fmt, ...) dlog_print(DLOG_ERROR, LOG_TAG, "%s: %s(%d) > " fmt, basename(const_cast<char*>(__FILE__)), __FUNCTION__, __LINE__, ##__VA_ARGS__)

#undef _W
#define _W(fmt, ...) dlog_print(DLOG_WARN, LOG_TAG, "%s: %s(%d) > " fmt, basename(const_cast<char*>(__FILE__)), __FUNCTION__, __LINE__, ##__VA_ARGS__)

#undef _I
#define _I(fmt, ...) dlog_print(DLOG_INFO, LOG_TAG, "%s: %s(%d) > " fmt, basename(const_cast<char*>(__FILE__)), __FUNCTION__, __LINE__, ##__VA_ARGS__)

#undef _D
#define _D(fmt, ...) dlog_print(DLOG_DEBUG, LOG_TAG, "%s: %s(%d) > " fmt, basename(const_cast<char*>(__FILE__)), __FUNCTION__, __LINE__, ##__VA_ARGS__)

#undef TIDL_VERSION
#define TIDL_VERSION "2.9.1"

#undef TIDL_VER_MAJOR
#define TIDL_VER_MAJOR 2

#undef TIDL_VER_MINOR
#define TIDL_VER_MINOR 9

#undef TIDL_VER_PATCH
#define TIDL_VER_PATCH 1

#undef EXPORT_API
#define EXPORT_API extern "C" __attribute__ ((visibility("default")))

namespace {

constexpr const uid_t kRegularUidMin = 5000;

bool IdleAddOnce(GMainContext* context, std::function<void()>* func) {
  auto* source = g_idle_source_new();
  if (source == nullptr) {
    _E("Failed to create idle source");
    return false;
  }

  g_source_set_callback(source, static_cast<GSourceFunc>(
  [](gpointer user_data) {
    auto* cb = static_cast<std::function<void()>*>(user_data);
    (*cb)();
    delete cb;
    return G_SOURCE_REMOVE;
  }), func, nullptr);
  g_source_attach(source, context);
  g_source_unref(source);
  return true;
}

std::shared_ptr<rpc_port::schedule_action_provider::LocalExecution> TizenActionSchedule_context_;

typedef enum {
  RPC_PORT_PARCEL_HEADER_UNKNOWN = 0b00000000,
  RPC_PORT_PARCEL_HEADER_IS_FROM_PROXY = 0b00000011,
  RPC_PORT_PARCEL_HEADER_LAN_C = 0b00000101,
  RPC_PORT_PARCEL_HEADER_LAN_CPP = 0b00001001,
  RPC_PORT_PARCEL_HEADER_LAN_CS = 0b00001101,
  RPC_PORT_PARCEL_HEADER_LAN_RUST = 0b00010001,
  RPC_PORT_PARCEL_HEADER_LAN_DART = 0b00010101,
} rpc_port_parcel_header_flags_e;

using rpc_port_parcel_reserve_t = int (*)(rpc_port_parcel_h h, unsigned int size);

using rpc_port_parcel_create_from_parcel_t = int (*)(rpc_port_parcel_h* h,
rpc_port_parcel_h origin_parcel,
unsigned int start_pos,
unsigned int size);
using rpc_port_parcel_set_data_size_t = int (*)(rpc_port_parcel_h h, unsigned int size);
using rpc_port_parcel_get_data_size_t = int (*)(rpc_port_parcel_h h, unsigned int* size);
using rpc_port_parcel_pin_t = int (*)(rpc_port_parcel_h h);
using rpc_port_parcel_get_reader_t = int (*)(rpc_port_parcel_h h, unsigned int* reader_pos);
using rpc_port_parcel_set_reader_t = int (*)(rpc_port_parcel_h h, unsigned int reader_pos);
using rpc_port_parcel_write_fd_t = int (*)(rpc_port_parcel_h h, int fd);
using rpc_port_parcel_read_fd_t = int (*)(rpc_port_parcel_h h, int* fd);
using rpc_port_parcel_clone_t = int (*)(rpc_port_parcel_h* h, rpc_port_parcel_h origin);
using rpc_port_get_peer_info_t = int (*)(rpc_port_h h, pid_t* pid, uid_t* uid);
using rpc_port_get_read_fd_t = int (*)(rpc_port_h h, int* fd);
using rpc_port_stub_has_pending_request_t = int (*)(rpc_port_stub_h h, bool* has_request);

using rpc_port_stub_has_privilege_local_t = int (*)(rpc_port_stub_h h, const char *appid, const char *privilege, bool *has_privilege);
using rpc_port_parcel_header_set_tag_ex_t = int (*)(rpc_port_parcel_header_h header,
unsigned char tidlc_version_major,
unsigned char tidlc_version_minor,
unsigned char tidlc_version_patch,
unsigned char tidl_protocol_ver,
unsigned char flags);
using rpc_port_parcel_header_get_tag_ex_t = int (*)(rpc_port_parcel_header_h header,
unsigned char* tidlc_version_major,
unsigned char* tidlc_version_minor,
unsigned char* tidlc_version_patch,
unsigned char* tidl_protocol_ver,
unsigned char* flags);

rpc_port_parcel_reserve_t dl_rpc_port_parcel_reserve;
rpc_port_parcel_create_from_parcel_t dl_rpc_port_parcel_create_from_parcel;
rpc_port_parcel_set_data_size_t dl_rpc_port_parcel_set_data_size;
rpc_port_parcel_get_data_size_t dl_rpc_port_parcel_get_data_size;
rpc_port_parcel_pin_t dl_rpc_port_parcel_pin;
rpc_port_parcel_get_reader_t dl_rpc_port_parcel_get_reader;
rpc_port_parcel_set_reader_t dl_rpc_port_parcel_set_reader;
rpc_port_parcel_write_fd_t dl_rpc_port_parcel_write_fd;
rpc_port_parcel_read_fd_t dl_rpc_port_parcel_read_fd;
rpc_port_parcel_clone_t dl_rpc_port_parcel_clone;
rpc_port_get_peer_info_t dl_rpc_port_get_peer_info;
rpc_port_get_read_fd_t dl_rpc_port_get_read_fd;
rpc_port_stub_has_pending_request_t dl_rpc_port_stub_has_pending_request;
rpc_port_parcel_header_set_tag_ex_t dl_rpc_port_parcel_header_set_tag_ex;
rpc_port_parcel_header_get_tag_ex_t dl_rpc_port_parcel_header_get_tag_ex;
rpc_port_stub_has_privilege_local_t dl_rpc_port_stub_has_privilege_local;

class RpcPortInternals {
 public:
  RpcPortInternals() {
    std::string symbol = "rpc_port_parcel_reserve";
    dl_rpc_port_parcel_reserve = reinterpret_cast<rpc_port_parcel_reserve_t>(
    dlsym(RTLD_DEFAULT, symbol.c_str()));
    if (dl_rpc_port_parcel_reserve == nullptr) {
      _E("Failed to find symbol(%s). Please check rpc-port version", symbol.c_str());
      return;
    }

    symbol = "rpc_port_parcel_create_from_parcel";
    dl_rpc_port_parcel_create_from_parcel = reinterpret_cast<rpc_port_parcel_create_from_parcel_t>(
    dlsym(RTLD_DEFAULT, symbol.c_str()));
    if (dl_rpc_port_parcel_create_from_parcel == nullptr) {
      _E("Failed to find symbol(%s). Please check rpc-port version", symbol.c_str());
      return;
    }

    symbol = "rpc_port_parcel_set_data_size";
    dl_rpc_port_parcel_set_data_size =
    reinterpret_cast<rpc_port_parcel_set_data_size_t>(
    dlsym(RTLD_DEFAULT, symbol.c_str()));
    if (dl_rpc_port_parcel_set_data_size == nullptr) {
      _E("Failed to find symbol(%s). Please check rpc-port version", symbol.c_str());
      return;
    }

    symbol = "rpc_port_parcel_get_data_size";
    dl_rpc_port_parcel_get_data_size =
    reinterpret_cast<rpc_port_parcel_get_data_size_t>(
    dlsym(RTLD_DEFAULT, symbol.c_str()));
    if (dl_rpc_port_parcel_get_data_size == nullptr) {
      _E("Failed to find symbol(%s). Please check rpc-port version", symbol.c_str());
      return;
    }

    symbol = "rpc_port_parcel_pin";
    dl_rpc_port_parcel_pin = reinterpret_cast<rpc_port_parcel_pin_t>(
    dlsym(RTLD_DEFAULT, symbol.c_str()));
    if (dl_rpc_port_parcel_pin == nullptr) {
      _E("Failed to find symbol(%s). Please check rpc-port version", symbol.c_str());
      return;
    }

    symbol = "rpc_port_parcel_get_reader";
    dl_rpc_port_parcel_get_reader = reinterpret_cast<rpc_port_parcel_get_reader_t>(
    dlsym(RTLD_DEFAULT, symbol.c_str()));
    if (dl_rpc_port_parcel_get_reader == nullptr) {
      _E("Failed to find symbol(%s). Please check rpc-port version", symbol.c_str());
      return;
    }

    symbol = "rpc_port_parcel_set_reader";
    dl_rpc_port_parcel_set_reader = reinterpret_cast<rpc_port_parcel_set_reader_t>(
    dlsym(RTLD_DEFAULT, symbol.c_str()));
    if (dl_rpc_port_parcel_set_reader == nullptr) {
      _E("Failed to find symbol(%s). Please check rpc-port version", symbol.c_str());
      return;
    }

    symbol = "rpc_port_parcel_write_fd";
    dl_rpc_port_parcel_write_fd = reinterpret_cast<rpc_port_parcel_write_fd_t>(
    dlsym(RTLD_DEFAULT, symbol.c_str()));
    if (dl_rpc_port_parcel_write_fd == nullptr) {
      _E("Failed to find symbol(%s). Please check rpc-port version", symbol.c_str());
      return;
    }

    symbol = "rpc_port_parcel_read_fd";
    dl_rpc_port_parcel_read_fd = reinterpret_cast<rpc_port_parcel_read_fd_t>(
    dlsym(RTLD_DEFAULT, symbol.c_str()));
    if (dl_rpc_port_parcel_read_fd == nullptr) {
      _E("Failed to find symbol(%s). Please check rpc-port version", symbol.c_str());
      return;
    }

    symbol = "rpc_port_parcel_clone";
    dl_rpc_port_parcel_clone = reinterpret_cast<rpc_port_parcel_clone_t>(
    dlsym(RTLD_DEFAULT, symbol.c_str()));
    if (dl_rpc_port_parcel_clone == nullptr) {
      _E("Failed to find symbol(%s). Please check rpc-port version", symbol.c_str());
      return;
    }

    symbol = "rpc_port_get_peer_info";
    dl_rpc_port_get_peer_info = reinterpret_cast<rpc_port_get_peer_info_t>(
    dlsym(RTLD_DEFAULT, symbol.c_str()));
    if (dl_rpc_port_get_peer_info == nullptr) {
      _E("Failed to find symbol(%s). Please check rpc-port version", symbol.c_str());
      return;
    }

    symbol = "rpc_port_get_read_fd";
    dl_rpc_port_get_read_fd = reinterpret_cast<rpc_port_get_read_fd_t>(
    dlsym(RTLD_DEFAULT, symbol.c_str()));
    if (dl_rpc_port_get_read_fd == nullptr) {
      _E("Failed to find symbol(%s). Please check rpc-port version", symbol.c_str());
      return;
    }

    symbol = "rpc_port_stub_has_pending_request";
    dl_rpc_port_stub_has_pending_request = reinterpret_cast<rpc_port_stub_has_pending_request_t>(
    dlsym(RTLD_DEFAULT, symbol.c_str()));
    if(dl_rpc_port_stub_has_pending_request == nullptr) {
      _E("Failed to find symbol(%s). Please check rpc-port version", symbol.c_str());
      return;
    }

    symbol = "rpc_port_parcel_header_set_tag_ex";
    dl_rpc_port_parcel_header_set_tag_ex = reinterpret_cast<rpc_port_parcel_header_set_tag_ex_t>(
    dlsym(RTLD_DEFAULT, symbol.c_str()));
    if (dl_rpc_port_parcel_header_set_tag_ex == nullptr) {
      _I("Failed to find symbol(%s). Ok, We will use old API", symbol.c_str());
    }

    symbol = "rpc_port_parcel_header_get_tag_ex";
    dl_rpc_port_parcel_header_get_tag_ex = reinterpret_cast<rpc_port_parcel_header_get_tag_ex_t>(
    dlsym(RTLD_DEFAULT, symbol.c_str()));
    if (dl_rpc_port_parcel_header_get_tag_ex == nullptr) {
      _I("Failed to find symbol(%s). Ok, We will use old API", symbol.c_str());
    }

    symbol = "rpc_port_stub_has_privilege_local";
    dl_rpc_port_stub_has_privilege_local = reinterpret_cast<rpc_port_stub_has_privilege_local_t>(
    dlsym(RTLD_DEFAULT, symbol.c_str()));
    if (dl_rpc_port_stub_has_privilege_local == nullptr) {
      _E("Failed to find symbol(%s). Please check rpc-port version", symbol.c_str());
      return;
    }
  }
};

RpcPortInternals rpc_port_internals_;

}  // namespace

namespace rpc_port {
namespace schedule_action_provider {

LocalExecution::LocalExecution(std::string port_name, LocalExecution::IEvent* listener) : port_name_(std::move(port_name)), listener_(listener), context_(g_main_context_ref_thread_default(), g_main_context_unref) {
  LoadSymbols();
}

void LocalExecution::Connect(void* context, bool sync) {
  if (connect_func_ != nullptr)
    connect_func_(context, sync);
}

void LocalExecution::Disconnect(void* context) {
  if (disconnect_func_ != nullptr)
    disconnect_func_(context);
}

void LocalExecution::SendResult(void* context, rpc_port_parcel_h parcel) {
  if (send_result_func_ != nullptr)
    send_result_func_(context, parcel);
}

void LocalExecution::InvokeCallback(void* context, rpc_port_parcel_h parcel) {
  if (invoke_callback_func_ != nullptr)
    invoke_callback_func_(context, parcel);
}

void LocalExecution::OnConnected(void* context, const std::string& sender, const std::string& instance, bool sync) {
  if (listener_ != nullptr)
    listener_->OnLocalConnected(context, sender, instance, sync);
}

void LocalExecution::OnDisconnected(void* context, const std::string& sender, const std::string& instance) {
  if (listener_ != nullptr)
    listener_->OnLocalDisconnected(context, sender, instance);
}

void LocalExecution::OnReceived(void* context, rpc_port_parcel_h parcel) {
  if (listener_ != nullptr)
    listener_->OnLocalReceived(context, parcel);
}

bool LocalExecution::LoadSymbols() {
  if (loaded_)
    return true;

  std::string symbol = "rpc_port_proxy_tizen_action_schedule_lem_" + port_name_ + "_connect";
  connect_func_ = reinterpret_cast<ProxyConnectFunc>(dlsym(RTLD_DEFAULT, symbol.c_str()));
  if (connect_func_ == nullptr) {
    _E("Failed to find symbol");
    return false;
  }

  symbol = "rpc_port_proxy_tizen_action_schedule_lem_" + port_name_ + "_disconnect";
  disconnect_func_ = reinterpret_cast<ProxyDisconnectFunc>(dlsym(RTLD_DEFAULT, symbol.c_str()));
  if (disconnect_func_ == nullptr) {
    _E("Failed to find symbol");
    return false;
  }

  symbol = "rpc_port_proxy_tizen_action_schedule_lem_" + port_name_ + "_send_result";
  send_result_func_ = reinterpret_cast<ProxySendResultFunc>(dlsym(RTLD_DEFAULT, symbol.c_str()));
  if (send_result_func_ == nullptr) {
    _E("Failed to find symbol");
    return false;
  }

  symbol = "rpc_port_proxy_tizen_action_schedule_lem_" + port_name_ + "_invoke_callback";
  invoke_callback_func_ = reinterpret_cast<ProxyInvokeCallbackFunc>(dlsym(RTLD_DEFAULT, symbol.c_str()));
  if (invoke_callback_func_ == nullptr) {
    _E("Failed to find symbol");
    return false;
  }

  loaded_ = true;
  return true;
}

void LocalExecution::SetListening(bool listening) {
  listening_ = listening;
}

bool LocalExecution::IsListening() const {
  return listening_;
}

GMainContext* LocalExecution::GetContext() const { return context_.get(); }

Bundle::Bundle() {
  handle_ = bundle_create();
  if (handle_ == nullptr)
    throw std::bad_alloc();
}

Bundle::Bundle(bundle* handle, bool copy, bool own) : handle_(handle), own_(own) {
  if (handle == nullptr)
    throw std::invalid_argument("handle is nullptr");

  if (copy) {
    handle_ = bundle_dup(handle);
    if (handle_ == nullptr)
      throw std::bad_alloc();
  }
}

Bundle::Bundle(std::string raw) {
  handle_ = bundle_decode(reinterpret_cast<const bundle_raw*>(raw.c_str()), raw.length());
  if (handle_ == nullptr)
    throw std::bad_alloc();
}

Bundle::~Bundle() {
  if (own_ && handle_)
    bundle_free(handle_);
}

Bundle::Bundle(const Bundle& b) {
  handle_ = bundle_dup(b.handle_);
  if (handle_ == nullptr)
    throw std::bad_alloc();
}

Bundle& Bundle::operator = (const Bundle& b) {
  if (this != &b) {
    if (handle_ && own_)
      bundle_free(handle_);

    handle_ = bundle_dup(b.handle_);
    if (handle_ == nullptr)
      throw std::bad_alloc();

    own_ = true;
  }

  return *this;
}

Bundle::Bundle(Bundle&& b) noexcept {
  handle_ = b.handle_;
  b.handle_ = bundle_create();
  own_ = b.own_;
  b.own_ = true;
}

Bundle& Bundle::operator = (Bundle&& b) noexcept {
  if (this != &b) {
    if (handle_ && own_)
      bundle_free(handle_);

    handle_ = b.handle_;
    b.handle_ = bundle_create();
    own_ = b.own_;
  }

  return *this;
}

bundle* Bundle::GetHandle() const {
  return handle_;
}

bundle* Bundle::Detach() {
  bundle* handle = handle_;
  handle_ = nullptr;
  return handle;
}

File::File(std::string filename) : filename_(std::move(filename)) {}

const std::string& File::GetFileName() const {
  return filename_;
}

int File::Share(rpc_port_h port) {
  int ret = rpc_port_set_private_sharing(port, filename_.c_str());
  if (ret != RPC_PORT_ERROR_NONE)
    _E("Failed to set private sharing. error(%d)", ret);

  return ret;
}

constexpr char kJsonObjOpen = 0x7b;
constexpr char kJsonObjClose = 0x7d;

inline std::string JsonEscape(const std::string& str) {
  static const char hex[] = "0123456789abcdef";
  std::string ret;
  for (const auto& ch : str) {
    if (ch == '"') {
      ret += "\\\"";
      continue;
    }

    if (ch == '\\') {
      ret += "\\\\";
      continue;
    }

    if (ch == '\b') {
      ret += "\\b";
      continue;
    }

    if (ch == '\f') {
      ret += "\\f";
      continue;
    }

    if (ch == '\n') {
      ret += "\\n";
      continue;
    }

    if (ch == '\r') {
      ret += "\\r";
      continue;
    }

    if (ch == '\t') {
      ret += "\\t";
      continue;
    }

    if (static_cast<unsigned char>(ch) < 0x20) {
      ret += "\\u00";
      ret += hex[(ch >> 4) & 0xf];
      ret += hex[ch & 0xf];
      continue;
    }

    ret += ch;
  }

  return ret;
}

inline void AppendToJson(std::string& json_str, bool value);
inline void AppendToJson(std::string& json_str, char value);
inline void AppendToJson(std::string& json_str, short value);
inline void AppendToJson(std::string& json_str, int value);
inline void AppendToJson(std::string& json_str, long long value);
inline void AppendToJson(std::string& json_str, unsigned char value);
inline void AppendToJson(std::string& json_str, unsigned short value);
inline void AppendToJson(std::string& json_str, unsigned int value);
inline void AppendToJson(std::string& json_str, unsigned long value);
inline void AppendToJson(std::string& json_str, float value);
inline void AppendToJson(std::string& json_str, double value);
inline void AppendToJson(std::string& json_str, const std::string& value);
inline void AppendToJson(std::string& json_str, const Bundle& value);
template <class T>
void AppendToJson(std::string& json_str, const std::list<T>& value);
template <class T>
void AppendToJson(std::string& json_str, const std::vector<T>& value);
template <class T>
void AppendToJson(std::string& json_str, const std::set<T>& value);
template <class K, class V>
void AppendToJson(std::string& json_str, const std::map<K, V>& value);
template <class T>
auto AppendToJson(std::string& json_str, const T& value)
-> decltype(value.ToJson(), void());
template <class T>
auto AppendToJson(std::string& json_str, const T& value)
-> decltype(value.GetFileName(), void());
template <class T>
auto AppendToJson(std::string& json_str, const T& value)
-> decltype(value.Get(), void());
template <class T>
auto AppendToJson(std::string& json_str, const T& value)
-> decltype(static_cast<long long>(value), void());

inline void AppendToJson(std::string& json_str, bool value) {
  json_str += value ? "true" : "false";
}

inline void AppendToJson(std::string& json_str, char value) {
  json_str += std::to_string(value);
}

inline void AppendToJson(std::string& json_str, short value) {
  json_str += std::to_string(value);
}

inline void AppendToJson(std::string& json_str, int value) {
  json_str += std::to_string(value);
}

inline void AppendToJson(std::string& json_str, long long value) {
  json_str += std::to_string(value);
}

inline void AppendToJson(std::string& json_str, unsigned char value) {
  json_str += std::to_string(value);
}

inline void AppendToJson(std::string& json_str, unsigned short value) {
  json_str += std::to_string(value);
}

inline void AppendToJson(std::string& json_str, unsigned int value) {
  json_str += std::to_string(value);
}

inline void AppendToJson(std::string& json_str, unsigned long value) {
  json_str += std::to_string(value);
}

inline void AppendToJson(std::string& json_str, float value) {
  json_str += std::to_string(value);
}

inline void AppendToJson(std::string& json_str, double value) {
  json_str += std::to_string(value);
}

inline void AppendToJson(std::string& json_str, const std::string& value) {
  json_str += "\"" + JsonEscape(value) + "\"";
}

inline void AppendToJson(std::string& json_str, const Bundle& value) {
  bundle_raw* raw = nullptr;
  int len = 0;
  bundle_encode(value.GetHandle(), &raw, &len);
  if (raw == nullptr) {
    json_str += "null";
    return;
  }

  json_str += "\"" + JsonEscape(std::string(reinterpret_cast<const char*>(raw), len)) + "\"";
  free(raw);
}

template <class T>
void AppendToJson(std::string& json_str, const std::list<T>& value) {
  json_str += "[";
  bool first = true;
  for (const auto& i : value) {
    if (!first) json_str += ",";
    first = false;
    AppendToJson(json_str, i);
  }

  json_str += "]";
}

template <class T>
void AppendToJson(std::string& json_str, const std::vector<T>& value) {
  json_str += "[";
  bool first = true;
  for (const auto& i : value) {
    if (!first) json_str += ",";
    first = false;
    AppendToJson(json_str, i);
  }

  json_str += "]";
}

template <class T>
void AppendToJson(std::string& json_str, const std::set<T>& value) {
  json_str += "[";
  bool first = true;
  for (const auto& i : value) {
    if (!first) json_str += ",";
    first = false;
    AppendToJson(json_str, i);
  }

  json_str += "]";
}

template <class K, class V>
void AppendToJson(std::string& json_str, const std::map<K, V>& value) {
  json_str += kJsonObjOpen;
  bool first = true;
  for (const auto& i : value) {
    if (!first) json_str += ",";
    first = false;
    std::string key_str;
    AppendToJson(key_str, i.first);
    if (key_str.empty() || key_str.front() != '"')
      key_str = "\"" + key_str + "\"";

    json_str += key_str + ":";
    AppendToJson(json_str, i.second);
  }

  json_str += kJsonObjClose;
}

template <class T>
auto AppendToJson(std::string& json_str, const T& value)
-> decltype(value.ToJson(), void()) {
  json_str += value.ToJson();
}

template <class T>
auto AppendToJson(std::string& json_str, const T& value)
-> decltype(value.GetFileName(), void()) {
  json_str += "\"" + JsonEscape(value.GetFileName()) + "\"";
}

template <class T>
auto AppendToJson(std::string& json_str, const T& value)
-> decltype(value.Get(), void()) {
  json_str += std::to_string(value.Get());
}

template <class T>
auto AppendToJson(std::string& json_str, const T& value)
-> decltype(static_cast<long long>(value), void()) {
  json_str += std::to_string(static_cast<long long>(value));
}

TizenEntity::TizenEntity() {}

TizenEntity::TizenEntity(std::string Id, std::string Extra) : Id_(std::move(Id)), Extra_(std::move(Extra)) {}

const std::string& TizenEntity::GetId() const {
  return Id_;
}

void TizenEntity::SetId(std::string Id) {
  Id_ = std::move(Id);
}

const std::string& TizenEntity::GetExtra() const {
  return Extra_;
}

void TizenEntity::SetExtra(std::string Extra) {
  Extra_ = std::move(Extra);
}

std::string TizenEntity::ToJson() const {
  std::string json_str;
  json_str += kJsonObjOpen;
  json_str += "\"TizenEntity\":";
  json_str += kJsonObjOpen;
  json_str += "\"Id\":";
  AppendToJson(json_str, GetId());
  json_str += ",\"Extra\":";
  AppendToJson(json_str, GetExtra());

  json_str += kJsonObjClose;
  json_str += kJsonObjClose;
  return json_str;
}

TizenEntityQuery::TizenEntityQuery() : Number_(0) {}

TizenEntityQuery::TizenEntityQuery(std::string Id, std::string Extra, std::string Keyword, std::string Category, int Number) : TizenEntity(std::move(Id), std::move(Extra)), Keyword_(std::move(Keyword)), Category_(std::move(Category)), Number_(Number) {}

const std::string& TizenEntityQuery::GetKeyword() const {
  return Keyword_;
}

void TizenEntityQuery::SetKeyword(std::string Keyword) {
  Keyword_ = std::move(Keyword);
}

const std::string& TizenEntityQuery::GetCategory() const {
  return Category_;
}

void TizenEntityQuery::SetCategory(std::string Category) {
  Category_ = std::move(Category);
}

int TizenEntityQuery::GetNumber() const {
  return Number_;
}

void TizenEntityQuery::SetNumber(int Number) {
  Number_ = Number;
}

std::string TizenEntityQuery::ToJson() const {
  std::string json_str;
  json_str += kJsonObjOpen;
  json_str += "\"TizenEntityQuery\":";
  json_str += kJsonObjOpen;
  json_str += "\"Id\":";
  AppendToJson(json_str, GetId());
  json_str += ",\"Extra\":";
  AppendToJson(json_str, GetExtra());
  json_str += ",\"Keyword\":";
  AppendToJson(json_str, GetKeyword());
  json_str += ",\"Category\":";
  AppendToJson(json_str, GetCategory());
  json_str += ",\"Number\":";
  AppendToJson(json_str, GetNumber());

  json_str += kJsonObjClose;
  json_str += kJsonObjClose;
  return json_str;
}

TizenEntityReminder::TizenEntityReminder() : Completed_(false) {}

TizenEntityReminder::TizenEntityReminder(std::string Id, std::string Extra, std::string Title, std::string DueDate, std::string Note, bool Completed) : TizenEntity(std::move(Id), std::move(Extra)), Title_(std::move(Title)), DueDate_(std::move(DueDate)), Note_(std::move(Note)), Completed_(Completed) {}

const std::string& TizenEntityReminder::GetTitle() const {
  return Title_;
}

void TizenEntityReminder::SetTitle(std::string Title) {
  Title_ = std::move(Title);
}

const std::string& TizenEntityReminder::GetDueDate() const {
  return DueDate_;
}

void TizenEntityReminder::SetDueDate(std::string DueDate) {
  DueDate_ = std::move(DueDate);
}

const std::string& TizenEntityReminder::GetNote() const {
  return Note_;
}

void TizenEntityReminder::SetNote(std::string Note) {
  Note_ = std::move(Note);
}

bool TizenEntityReminder::GetCompleted() const {
  return Completed_;
}

void TizenEntityReminder::SetCompleted(bool Completed) {
  Completed_ = Completed;
}

std::string TizenEntityReminder::ToJson() const {
  std::string json_str;
  json_str += kJsonObjOpen;
  json_str += "\"TizenEntityReminder\":";
  json_str += kJsonObjOpen;
  json_str += "\"Id\":";
  AppendToJson(json_str, GetId());
  json_str += ",\"Extra\":";
  AppendToJson(json_str, GetExtra());
  json_str += ",\"Title\":";
  AppendToJson(json_str, GetTitle());
  json_str += ",\"DueDate\":";
  AppendToJson(json_str, GetDueDate());
  json_str += ",\"Note\":";
  AppendToJson(json_str, GetNote());
  json_str += ",\"Completed\":";
  AppendToJson(json_str, GetCompleted());

  json_str += kJsonObjClose;
  json_str += kJsonObjClose;
  return json_str;
}

TizenEntityChannel::TizenEntityChannel() : Major_(0), Minor_(0), ServiceId_(0) {}

TizenEntityChannel::TizenEntityChannel(std::string Id, std::string Extra, int Major, int Minor, std::string Name, int ServiceId, std::string Source, std::string Signal) : TizenEntity(std::move(Id), std::move(Extra)), Major_(Major), Minor_(Minor), Name_(std::move(Name)), ServiceId_(ServiceId), Source_(std::move(Source)), Signal_(std::move(Signal)) {}

int TizenEntityChannel::GetMajor() const {
  return Major_;
}

void TizenEntityChannel::SetMajor(int Major) {
  Major_ = Major;
}

int TizenEntityChannel::GetMinor() const {
  return Minor_;
}

void TizenEntityChannel::SetMinor(int Minor) {
  Minor_ = Minor;
}

const std::string& TizenEntityChannel::GetName() const {
  return Name_;
}

void TizenEntityChannel::SetName(std::string Name) {
  Name_ = std::move(Name);
}

int TizenEntityChannel::GetServiceId() const {
  return ServiceId_;
}

void TizenEntityChannel::SetServiceId(int ServiceId) {
  ServiceId_ = ServiceId;
}

const std::string& TizenEntityChannel::GetSource() const {
  return Source_;
}

void TizenEntityChannel::SetSource(std::string Source) {
  Source_ = std::move(Source);
}

const std::string& TizenEntityChannel::GetSignal() const {
  return Signal_;
}

void TizenEntityChannel::SetSignal(std::string Signal) {
  Signal_ = std::move(Signal);
}

std::string TizenEntityChannel::ToJson() const {
  std::string json_str;
  json_str += kJsonObjOpen;
  json_str += "\"TizenEntityChannel\":";
  json_str += kJsonObjOpen;
  json_str += "\"Id\":";
  AppendToJson(json_str, GetId());
  json_str += ",\"Extra\":";
  AppendToJson(json_str, GetExtra());
  json_str += ",\"Major\":";
  AppendToJson(json_str, GetMajor());
  json_str += ",\"Minor\":";
  AppendToJson(json_str, GetMinor());
  json_str += ",\"Name\":";
  AppendToJson(json_str, GetName());
  json_str += ",\"ServiceId\":";
  AppendToJson(json_str, GetServiceId());
  json_str += ",\"Source\":";
  AppendToJson(json_str, GetSource());
  json_str += ",\"Signal\":";
  AppendToJson(json_str, GetSignal());

  json_str += kJsonObjClose;
  json_str += kJsonObjClose;
  return json_str;
}

TizenEntityProgram::TizenEntityProgram() : IsLive_(false) {}

TizenEntityProgram::TizenEntityProgram(std::string Id, std::string Extra, std::string Title, TizenEntityChannel Channel, std::string StartTime, std::string EndTime, std::string Genre, std::string Rating, std::string Description, bool IsLive) : TizenEntity(std::move(Id), std::move(Extra)), Title_(std::move(Title)), Channel_(std::move(Channel)), StartTime_(std::move(StartTime)), EndTime_(std::move(EndTime)), Genre_(std::move(Genre)), Rating_(std::move(Rating)), Description_(std::move(Description)), IsLive_(IsLive) {}

const std::string& TizenEntityProgram::GetTitle() const {
  return Title_;
}

void TizenEntityProgram::SetTitle(std::string Title) {
  Title_ = std::move(Title);
}

const TizenEntityChannel& TizenEntityProgram::GetChannel() const {
  return Channel_;
}

void TizenEntityProgram::SetChannel(TizenEntityChannel Channel) {
  Channel_ = std::move(Channel);
}

const std::string& TizenEntityProgram::GetStartTime() const {
  return StartTime_;
}

void TizenEntityProgram::SetStartTime(std::string StartTime) {
  StartTime_ = std::move(StartTime);
}

const std::string& TizenEntityProgram::GetEndTime() const {
  return EndTime_;
}

void TizenEntityProgram::SetEndTime(std::string EndTime) {
  EndTime_ = std::move(EndTime);
}

const std::string& TizenEntityProgram::GetGenre() const {
  return Genre_;
}

void TizenEntityProgram::SetGenre(std::string Genre) {
  Genre_ = std::move(Genre);
}

const std::string& TizenEntityProgram::GetRating() const {
  return Rating_;
}

void TizenEntityProgram::SetRating(std::string Rating) {
  Rating_ = std::move(Rating);
}

const std::string& TizenEntityProgram::GetDescription() const {
  return Description_;
}

void TizenEntityProgram::SetDescription(std::string Description) {
  Description_ = std::move(Description);
}

bool TizenEntityProgram::GetIsLive() const {
  return IsLive_;
}

void TizenEntityProgram::SetIsLive(bool IsLive) {
  IsLive_ = IsLive;
}

std::string TizenEntityProgram::ToJson() const {
  std::string json_str;
  json_str += kJsonObjOpen;
  json_str += "\"TizenEntityProgram\":";
  json_str += kJsonObjOpen;
  json_str += "\"Id\":";
  AppendToJson(json_str, GetId());
  json_str += ",\"Extra\":";
  AppendToJson(json_str, GetExtra());
  json_str += ",\"Title\":";
  AppendToJson(json_str, GetTitle());
  json_str += ",\"Channel\":";
  AppendToJson(json_str, GetChannel());
  json_str += ",\"StartTime\":";
  AppendToJson(json_str, GetStartTime());
  json_str += ",\"EndTime\":";
  AppendToJson(json_str, GetEndTime());
  json_str += ",\"Genre\":";
  AppendToJson(json_str, GetGenre());
  json_str += ",\"Rating\":";
  AppendToJson(json_str, GetRating());
  json_str += ",\"Description\":";
  AppendToJson(json_str, GetDescription());
  json_str += ",\"IsLive\":";
  AppendToJson(json_str, GetIsLive());

  json_str += kJsonObjClose;
  json_str += kJsonObjClose;
  return json_str;
}

TizenEntityReservation::TizenEntityReservation() {}

TizenEntityReservation::TizenEntityReservation(std::string Id, std::string Extra, TizenEntityChannel Channel, TizenEntityProgram Program, std::string StartTime, std::string EndTime, std::string Repeat, std::string Kind) : TizenEntity(std::move(Id), std::move(Extra)), Channel_(std::move(Channel)), Program_(std::move(Program)), StartTime_(std::move(StartTime)), EndTime_(std::move(EndTime)), Repeat_(std::move(Repeat)), Kind_(std::move(Kind)) {}

const TizenEntityChannel& TizenEntityReservation::GetChannel() const {
  return Channel_;
}

void TizenEntityReservation::SetChannel(TizenEntityChannel Channel) {
  Channel_ = std::move(Channel);
}

const TizenEntityProgram& TizenEntityReservation::GetProgram() const {
  return Program_;
}

void TizenEntityReservation::SetProgram(TizenEntityProgram Program) {
  Program_ = std::move(Program);
}

const std::string& TizenEntityReservation::GetStartTime() const {
  return StartTime_;
}

void TizenEntityReservation::SetStartTime(std::string StartTime) {
  StartTime_ = std::move(StartTime);
}

const std::string& TizenEntityReservation::GetEndTime() const {
  return EndTime_;
}

void TizenEntityReservation::SetEndTime(std::string EndTime) {
  EndTime_ = std::move(EndTime);
}

const std::string& TizenEntityReservation::GetRepeat() const {
  return Repeat_;
}

void TizenEntityReservation::SetRepeat(std::string Repeat) {
  Repeat_ = std::move(Repeat);
}

const std::string& TizenEntityReservation::GetKind() const {
  return Kind_;
}

void TizenEntityReservation::SetKind(std::string Kind) {
  Kind_ = std::move(Kind);
}

std::string TizenEntityReservation::ToJson() const {
  std::string json_str;
  json_str += kJsonObjOpen;
  json_str += "\"TizenEntityReservation\":";
  json_str += kJsonObjOpen;
  json_str += "\"Id\":";
  AppendToJson(json_str, GetId());
  json_str += ",\"Extra\":";
  AppendToJson(json_str, GetExtra());
  json_str += ",\"Channel\":";
  AppendToJson(json_str, GetChannel());
  json_str += ",\"Program\":";
  AppendToJson(json_str, GetProgram());
  json_str += ",\"StartTime\":";
  AppendToJson(json_str, GetStartTime());
  json_str += ",\"EndTime\":";
  AppendToJson(json_str, GetEndTime());
  json_str += ",\"Repeat\":";
  AppendToJson(json_str, GetRepeat());
  json_str += ",\"Kind\":";
  AppendToJson(json_str, GetKind());

  json_str += kJsonObjClose;
  json_str += kJsonObjClose;
  return json_str;
}

TizenEntityStatus::TizenEntityStatus() : Success_(false) {}

TizenEntityStatus::TizenEntityStatus(bool Success, std::string Reason) : Success_(Success), Reason_(std::move(Reason)) {}

bool TizenEntityStatus::GetSuccess() const {
  return Success_;
}

void TizenEntityStatus::SetSuccess(bool Success) {
  Success_ = Success;
}

const std::string& TizenEntityStatus::GetReason() const {
  return Reason_;
}

void TizenEntityStatus::SetReason(std::string Reason) {
  Reason_ = std::move(Reason);
}

std::string TizenEntityStatus::ToJson() const {
  std::string json_str;
  json_str += kJsonObjOpen;
  json_str += "\"TizenEntityStatus\":";
  json_str += kJsonObjOpen;
  json_str += "\"Success\":";
  AppendToJson(json_str, GetSuccess());
  json_str += ",\"Reason\":";
  AppendToJson(json_str, GetReason());

  json_str += kJsonObjClose;
  json_str += kJsonObjClose;
  return json_str;
}

namespace stub {

RemoteException::RemoteException() {}

RemoteException::RemoteException(std::string message) : message_(std::move(message)) {}

RemoteException::RemoteException(int cause, std::string message) : cause_(cause), message_(std::move(message)) {}

int RemoteException::GetCause() const {
  return cause_;
}

const std::string& RemoteException::GetMessage() const {
  return message_;
}

class Unit {
 public:
  Unit() {}

  Unit(int32_t name, int32_t type) : name_(name), type_(type) {}

  const int32_t& GetName() const { return name_; }

  void SetName(int32_t name) { name_ = name; }

  const int32_t& GetType() const { return type_; }

  void SetType(int32_t type) { type_ = type; }

  void Serialize(rpc_port_parcel_h parcel) {
    rpc_port_parcel_write_int32(parcel, name_);
    rpc_port_parcel_write_int32(parcel, type_);

    unsigned int size_pos = 0;
    dl_rpc_port_parcel_get_data_size(parcel, &size_pos);
    dl_rpc_port_parcel_reserve(parcel, sizeof(unsigned int));

    for (auto& i : cmds_) {
      i(parcel);
    }

    unsigned int cur_pos;
    dl_rpc_port_parcel_get_data_size(parcel, &cur_pos);
    size_t size = cur_pos - size_pos - sizeof(unsigned int);
    dl_rpc_port_parcel_set_data_size(parcel, size_pos);
    rpc_port_parcel_write_int32(parcel, size);
    dl_rpc_port_parcel_set_data_size(parcel, cur_pos);
    cmds_.clear();
  }

  void Deserialize(rpc_port_parcel_h parcel) {
    rpc_port_parcel_read_int32(parcel, reinterpret_cast<int*>(&name_));
    rpc_port_parcel_read_int32(parcel, reinterpret_cast<int*>(&type_));

    int size = 0;
    rpc_port_parcel_read_array_count(parcel, &size);
    if (size == 0) return;

    uint32_t start_pos = 0;
    dl_rpc_port_parcel_get_reader(parcel, &start_pos);

    rpc_port_parcel_h sub_parcel_raw = nullptr;
    dl_rpc_port_parcel_create_from_parcel(&sub_parcel_raw, parcel, start_pos,
    size);
    sub_parcel_.reset(sub_parcel_raw);
    dl_rpc_port_parcel_reserve(sub_parcel_.get(), size);
    dl_rpc_port_parcel_set_reader(parcel, start_pos + size);
  }

  void Write(const std::vector<TizenEntityReminder>& value, rpc_port_parcel_h parcel = nullptr);
  void Read(std::vector<TizenEntityReminder>& value);

  void Write(const TizenActionSchedule::CallbackBase& value, rpc_port_parcel_h parcel = nullptr);
  void Read(TizenActionSchedule::CallbackBase& value);

  void Write(const int& value, rpc_port_parcel_h parcel = nullptr);
  void Read(int& value);

  void Write(const TizenEntity& value, rpc_port_parcel_h parcel = nullptr);
  void Read(TizenEntity& value);

  void Write(const bool& value, rpc_port_parcel_h parcel = nullptr);
  void Read(bool& value);

  void Write(const std::string& value, rpc_port_parcel_h parcel = nullptr);
  void Read(std::string& value);

  void Write(const TizenEntityProgram& value, rpc_port_parcel_h parcel = nullptr);
  void Read(TizenEntityProgram& value);

  void Write(const Bundle& value, rpc_port_parcel_h parcel = nullptr);
  void Read(Bundle& value);

  void Write(const RemoteException& value, rpc_port_parcel_h parcel = nullptr);
  void Read(RemoteException& value);

  void Write(const File& value, rpc_port_parcel_h parcel = nullptr);
  void Read(File& value);

  void Write(const TizenEntityReminder& value, rpc_port_parcel_h parcel = nullptr);
  void Read(TizenEntityReminder& value);

  void Write(const TizenEntityStatus& value, rpc_port_parcel_h parcel = nullptr);
  void Read(TizenEntityStatus& value);

  void Write(const std::vector<TizenEntityReservation>& value, rpc_port_parcel_h parcel = nullptr);
  void Read(std::vector<TizenEntityReservation>& value);

  void Write(const TizenEntityQuery& value, rpc_port_parcel_h parcel = nullptr);
  void Read(TizenEntityQuery& value);

  void Write(const TizenEntityChannel& value, rpc_port_parcel_h parcel = nullptr);
  void Read(TizenEntityChannel& value);

  void Write(const TizenEntityReservation& value, rpc_port_parcel_h parcel = nullptr);
  void Read(TizenEntityReservation& value);

 private:
  int32_t name_ = 0;
  int32_t type_ = 0;
  std::vector<std::function<void(rpc_port_parcel_h)>> cmds_;
  std::unique_ptr<std::remove_pointer_t<rpc_port_parcel_h>,
  decltype(rpc_port_parcel_destroy)*>
  sub_parcel_{nullptr, rpc_port_parcel_destroy};
};

class UnitMap {
 public:
  UnitMap() {}

  void Clear() { map_.clear(); }

  size_t GetSize() const { return map_.size(); }

  void Insert(int32_t name, std::shared_ptr<Unit> unit) {
    map_[name] = std::move(unit);
  }

  std::shared_ptr<Unit> Lookup(int32_t name) const {
    auto found = map_.find(name);
    if (found == map_.end()) return nullptr;

    return found->second;
  }

  void Serialize(rpc_port_parcel_h parcel) const && {
    rpc_port_parcel_write_array_count(parcel, GetSize() & INT_MAX);
    for (auto& iter : map_) {
      auto& unit = iter.second;
      unit->Serialize(parcel);
    }
  }

  void Deserialize(rpc_port_parcel_h parcel) {
    int size = 0;
    rpc_port_parcel_read_array_count(parcel, &size);
    dl_rpc_port_parcel_pin(parcel);
    for (int i = 0; i < size; ++i) {
      auto unit = std::make_shared<Unit>();
      unit->Deserialize(parcel);
      auto name = unit->GetName();
      Insert(name, std::move(unit));
    }
  }

  void Read(int32_t name, std::vector<TizenEntityReminder>& value) const {
    auto unit = Lookup(name);
    if (unit == nullptr) {
      _E("Failed to find %d", name);
      return;
    }

    if (unit->GetType() != -124622307 /*array_TizenEntityReminder*/) {
      _E("type(%d) is not -124622307", unit->GetType());
      return;
    }

    unit->Read(value);
  }

  UnitMap&& Write(int32_t name, const std::vector<TizenEntityReminder>& value) && {
    auto unit = std::make_shared<Unit>(name, -124622307 /*array_TizenEntityReminder*/);
    unit->Write(value);
    Insert(name, std::move(unit));
    return std::move(*this);
  }

  void Read(int32_t name, TizenActionSchedule::CallbackBase& value) const {
    auto unit = Lookup(name);
    if (unit == nullptr) {
      _E("Failed to find %d", name);
      return;
    }

    if (unit->GetType() != 819322245 /*delegate*/) {
      _E("type(%d) is not 819322245", unit->GetType());
      return;
    }

    unit->Read(value);
  }

  UnitMap&& Write(int32_t name, const TizenActionSchedule::CallbackBase& value) && {
    auto unit = std::make_shared<Unit>(name, 819322245 /*delegate*/);
    unit->Write(value);
    Insert(name, std::move(unit));
    return std::move(*this);
  }

  void Read(int32_t name, int& value) const {
    auto unit = Lookup(name);
    if (unit == nullptr) {
      _E("Failed to find %d", name);
      return;
    }

    if (unit->GetType() != 104431 /*int*/) {
      _E("type(%d) is not 104431", unit->GetType());
      return;
    }

    unit->Read(value);
  }

  UnitMap&& Write(int32_t name, const int& value) && {
    auto unit = std::make_shared<Unit>(name, 104431 /*int*/);
    unit->Write(value);
    Insert(name, std::move(unit));
    return std::move(*this);
  }

  void Read(int32_t name, TizenEntity& value) const {
    auto unit = Lookup(name);
    if (unit == nullptr) {
      _E("Failed to find %d", name);
      return;
    }

    if (unit->GetType() != -393351823 /*TizenEntity*/) {
      _E("type(%d) is not -393351823", unit->GetType());
      return;
    }

    unit->Read(value);
  }

  UnitMap&& Write(int32_t name, const TizenEntity& value) && {
    auto unit = std::make_shared<Unit>(name, -393351823 /*TizenEntity*/);
    unit->Write(value);
    Insert(name, std::move(unit));
    return std::move(*this);
  }

  void Read(int32_t name, bool& value) const {
    auto unit = Lookup(name);
    if (unit == nullptr) {
      _E("Failed to find %d", name);
      return;
    }

    if (unit->GetType() != 3029738 /*bool*/) {
      _E("type(%d) is not 3029738", unit->GetType());
      return;
    }

    unit->Read(value);
  }

  UnitMap&& Write(int32_t name, const bool& value) && {
    auto unit = std::make_shared<Unit>(name, 3029738 /*bool*/);
    unit->Write(value);
    Insert(name, std::move(unit));
    return std::move(*this);
  }

  void Read(int32_t name, std::string& value) const {
    auto unit = Lookup(name);
    if (unit == nullptr) {
      _E("Failed to find %d", name);
      return;
    }

    if (unit->GetType() != -891985903 /*string*/) {
      _E("type(%d) is not -891985903", unit->GetType());
      return;
    }

    unit->Read(value);
  }

  UnitMap&& Write(int32_t name, const std::string& value) && {
    auto unit = std::make_shared<Unit>(name, -891985903 /*string*/);
    unit->Write(value);
    Insert(name, std::move(unit));
    return std::move(*this);
  }

  void Read(int32_t name, TizenEntityProgram& value) const {
    auto unit = Lookup(name);
    if (unit == nullptr) {
      _E("Failed to find %d", name);
      return;
    }

    if (unit->GetType() != -827819516 /*TizenEntity::TizenEntityProgram*/) {
      _E("type(%d) is not -827819516", unit->GetType());
      return;
    }

    unit->Read(value);
  }

  UnitMap&& Write(int32_t name, const TizenEntityProgram& value) && {
    auto unit = std::make_shared<Unit>(name, -827819516 /*TizenEntity::TizenEntityProgram*/);
    unit->Write(value);
    Insert(name, std::move(unit));
    return std::move(*this);
  }

  void Read(int32_t name, Bundle& value) const {
    auto unit = Lookup(name);
    if (unit == nullptr) {
      _E("Failed to find %d", name);
      return;
    }

    if (unit->GetType() != -1377881982 /*bundle*/) {
      _E("type(%d) is not -1377881982", unit->GetType());
      return;
    }

    unit->Read(value);
  }

  UnitMap&& Write(int32_t name, const Bundle& value) && {
    auto unit = std::make_shared<Unit>(name, -1377881982 /*bundle*/);
    unit->Write(value);
    Insert(name, std::move(unit));
    return std::move(*this);
  }

  void Read(int32_t name, RemoteException& value) const {
    auto unit = Lookup(name);
    if (unit == nullptr) {
      _E("Failed to find %d", name);
      return;
    }

    if (unit->GetType() != -1223777386 /*remote_exception*/) {
      _E("type(%d) is not -1223777386", unit->GetType());
      return;
    }

    unit->Read(value);
  }

  UnitMap&& Write(int32_t name, const RemoteException& value) && {
    auto unit = std::make_shared<Unit>(name, -1223777386 /*remote_exception*/);
    unit->Write(value);
    Insert(name, std::move(unit));
    return std::move(*this);
  }

  void Read(int32_t name, File& value) const {
    auto unit = Lookup(name);
    if (unit == nullptr) {
      _E("Failed to find %d", name);
      return;
    }

    if (unit->GetType() != 3143036 /*file*/) {
      _E("type(%d) is not 3143036", unit->GetType());
      return;
    }

    unit->Read(value);
  }

  UnitMap&& Write(int32_t name, const File& value) && {
    auto unit = std::make_shared<Unit>(name, 3143036 /*file*/);
    unit->Write(value);
    Insert(name, std::move(unit));
    return std::move(*this);
  }

  void Read(int32_t name, TizenEntityReminder& value) const {
    auto unit = Lookup(name);
    if (unit == nullptr) {
      _E("Failed to find %d", name);
      return;
    }

    if (unit->GetType() != 589878514 /*TizenEntity::TizenEntityReminder*/) {
      _E("type(%d) is not 589878514", unit->GetType());
      return;
    }

    unit->Read(value);
  }

  UnitMap&& Write(int32_t name, const TizenEntityReminder& value) && {
    auto unit = std::make_shared<Unit>(name, 589878514 /*TizenEntity::TizenEntityReminder*/);
    unit->Write(value);
    Insert(name, std::move(unit));
    return std::move(*this);
  }

  void Read(int32_t name, TizenEntityStatus& value) const {
    auto unit = Lookup(name);
    if (unit == nullptr) {
      _E("Failed to find %d", name);
      return;
    }

    if (unit->GetType() != -1652879165 /*TizenEntityStatus*/) {
      _E("type(%d) is not -1652879165", unit->GetType());
      return;
    }

    unit->Read(value);
  }

  UnitMap&& Write(int32_t name, const TizenEntityStatus& value) && {
    auto unit = std::make_shared<Unit>(name, -1652879165 /*TizenEntityStatus*/);
    unit->Write(value);
    Insert(name, std::move(unit));
    return std::move(*this);
  }

  void Read(int32_t name, std::vector<TizenEntityReservation>& value) const {
    auto unit = Lookup(name);
    if (unit == nullptr) {
      _E("Failed to find %d", name);
      return;
    }

    if (unit->GetType() != 1654306369 /*array_TizenEntityReservation*/) {
      _E("type(%d) is not 1654306369", unit->GetType());
      return;
    }

    unit->Read(value);
  }

  UnitMap&& Write(int32_t name, const std::vector<TizenEntityReservation>& value) && {
    auto unit = std::make_shared<Unit>(name, 1654306369 /*array_TizenEntityReservation*/);
    unit->Write(value);
    Insert(name, std::move(unit));
    return std::move(*this);
  }

  void Read(int32_t name, TizenEntityQuery& value) const {
    auto unit = Lookup(name);
    if (unit == nullptr) {
      _E("Failed to find %d", name);
      return;
    }

    if (unit->GetType() != -1389800376 /*TizenEntity::TizenEntityQuery*/) {
      _E("type(%d) is not -1389800376", unit->GetType());
      return;
    }

    unit->Read(value);
  }

  UnitMap&& Write(int32_t name, const TizenEntityQuery& value) && {
    auto unit = std::make_shared<Unit>(name, -1389800376 /*TizenEntity::TizenEntityQuery*/);
    unit->Write(value);
    Insert(name, std::move(unit));
    return std::move(*this);
  }

  void Read(int32_t name, TizenEntityChannel& value) const {
    auto unit = Lookup(name);
    if (unit == nullptr) {
      _E("Failed to find %d", name);
      return;
    }

    if (unit->GetType() != 220518531 /*TizenEntity::TizenEntityChannel*/) {
      _E("type(%d) is not 220518531", unit->GetType());
      return;
    }

    unit->Read(value);
  }

  UnitMap&& Write(int32_t name, const TizenEntityChannel& value) && {
    auto unit = std::make_shared<Unit>(name, 220518531 /*TizenEntity::TizenEntityChannel*/);
    unit->Write(value);
    Insert(name, std::move(unit));
    return std::move(*this);
  }

  void Read(int32_t name, TizenEntityReservation& value) const {
    auto unit = Lookup(name);
    if (unit == nullptr) {
      _E("Failed to find %d", name);
      return;
    }

    if (unit->GetType() != 1490345804 /*TizenEntity::TizenEntityReservation*/) {
      _E("type(%d) is not 1490345804", unit->GetType());
      return;
    }

    unit->Read(value);
  }

  UnitMap&& Write(int32_t name, const TizenEntityReservation& value) && {
    auto unit = std::make_shared<Unit>(name, 1490345804 /*TizenEntity::TizenEntityReservation*/);
    unit->Write(value);
    Insert(name, std::move(unit));
    return std::move(*this);
  }

 private:
  std::unordered_map<int32_t, std::shared_ptr<Unit>> map_;
};

void Unit::Write(const std::vector<TizenEntityReminder>& value, rpc_port_parcel_h parcel) {
  auto cb = [&value, this](auto* p) {
    rpc_port_parcel_write_array_count(p, static_cast<int>(value.size() & INT_MAX));

    for (auto& i : value)
      Write(i, p);

  };

  if (parcel)
    cb(parcel);
  else
    cmds_.push_back(std::move(cb));
}

void Unit::Read(std::vector<TizenEntityReminder>& value) {
  int tmp_size = 0;
  rpc_port_parcel_read_array_count(sub_parcel_.get(), &tmp_size);

  for (int index = 0; index < tmp_size; ++index) {
    TizenEntityReminder tmp_value;
    Read(tmp_value);
    value.push_back(tmp_value);
  }

}

void Unit::Write(const TizenActionSchedule::CallbackBase& value, rpc_port_parcel_h parcel) {
  auto cb = [&value, this](auto* p) {
    rpc_port_parcel_write_int32(p, value.GetId());
    rpc_port_parcel_write_int32(p, value.GetSeqId());
    rpc_port_parcel_write_bool(p, value.IsOnce());

  };

  if (parcel)
    cb(parcel);
  else
    cmds_.push_back(std::move(cb));
}

void Unit::Read(TizenActionSchedule::CallbackBase& value) {
  int id = 0;
  int seq_id = 0;
  bool once = false;

  rpc_port_parcel_read_int32(sub_parcel_.get(), &id);
  rpc_port_parcel_read_int32(sub_parcel_.get(), &seq_id);
  rpc_port_parcel_read_bool(sub_parcel_.get(), &once);

  value.SetId(id);
  value.SetSeqId(seq_id);
  value.SetOnce(once);

}

void Unit::Write(const int& value, rpc_port_parcel_h parcel) {
  auto cb = [value, this](auto* p) {
    rpc_port_parcel_burst_write(p, reinterpret_cast<const unsigned char*>(&value), sizeof(int));

  };

  if (parcel)
    cb(parcel);
  else
    cmds_.push_back(std::move(cb));
}

void Unit::Read(int& value) {
  int tmp_value = 0;
  rpc_port_parcel_burst_read(sub_parcel_.get(), reinterpret_cast<unsigned char*>(&tmp_value), sizeof(int));
  value = tmp_value;

}

void Unit::Write(const TizenEntity& value, rpc_port_parcel_h parcel) {
  auto cb = [&value, this](auto* p) {
    Write(value.GetId(), p);

    Write(value.GetExtra(), p);

  };

  if (parcel)
    cb(parcel);
  else
    cmds_.push_back(std::move(cb));
}

void Unit::Read(TizenEntity& value) {
  std::string tmp_Id;
  Read(tmp_Id);
  value.SetId(tmp_Id);

  std::string tmp_Extra;
  Read(tmp_Extra);
  value.SetExtra(tmp_Extra);

}

void Unit::Write(const bool& value, rpc_port_parcel_h parcel) {
  auto cb = [value, this](auto* p) {
    rpc_port_parcel_burst_write(p, reinterpret_cast<const unsigned char*>(&value), sizeof(bool));

  };

  if (parcel)
    cb(parcel);
  else
    cmds_.push_back(std::move(cb));
}

void Unit::Read(bool& value) {
  bool tmp_value = false;
  rpc_port_parcel_burst_read(sub_parcel_.get(), reinterpret_cast<unsigned char*>(&tmp_value), sizeof(bool));
  value = tmp_value;

}

void Unit::Write(const std::string& value, rpc_port_parcel_h parcel) {
  auto cb = [&value, this](auto* p) {
    rpc_port_parcel_write_string(p, value.c_str());

  };

  if (parcel)
    cb(parcel);
  else
    cmds_.push_back(std::move(cb));
}

void Unit::Read(std::string& value) {
  char* tmp_str = nullptr;
  rpc_port_parcel_read_string(sub_parcel_.get(), &tmp_str);
  if (tmp_str != nullptr) {
    value = std::string(tmp_str);
    free(tmp_str);
  }

}

void Unit::Write(const TizenEntityProgram& value, rpc_port_parcel_h parcel) {
  auto cb = [&value, this](auto* p) {
    Write(value.GetId(), p);

    Write(value.GetExtra(), p);

    Write(value.GetTitle(), p);

    Write(value.GetChannel(), p);

    Write(value.GetStartTime(), p);

    Write(value.GetEndTime(), p);

    Write(value.GetGenre(), p);

    Write(value.GetRating(), p);

    Write(value.GetDescription(), p);

    Write(value.GetIsLive(), p);

  };

  if (parcel)
    cb(parcel);
  else
    cmds_.push_back(std::move(cb));
}

void Unit::Read(TizenEntityProgram& value) {
  std::string tmp_Id;
  Read(tmp_Id);
  value.SetId(tmp_Id);

  std::string tmp_Extra;
  Read(tmp_Extra);
  value.SetExtra(tmp_Extra);

  std::string tmp_Title;
  Read(tmp_Title);
  value.SetTitle(tmp_Title);

  TizenEntityChannel tmp_Channel;
  Read(tmp_Channel);
  value.SetChannel(tmp_Channel);

  std::string tmp_StartTime;
  Read(tmp_StartTime);
  value.SetStartTime(tmp_StartTime);

  std::string tmp_EndTime;
  Read(tmp_EndTime);
  value.SetEndTime(tmp_EndTime);

  std::string tmp_Genre;
  Read(tmp_Genre);
  value.SetGenre(tmp_Genre);

  std::string tmp_Rating;
  Read(tmp_Rating);
  value.SetRating(tmp_Rating);

  std::string tmp_Description;
  Read(tmp_Description);
  value.SetDescription(tmp_Description);

  bool tmp_IsLive = false;
  Read(tmp_IsLive);
  value.SetIsLive(tmp_IsLive);

}

void Unit::Write(const Bundle& value, rpc_port_parcel_h parcel) {
  auto cb = [&value, this](auto* p) {
    rpc_port_parcel_write_bundle(p, value.GetHandle());

  };

  if (parcel)
    cb(parcel);
  else
    cmds_.push_back(std::move(cb));
}

void Unit::Read(Bundle& value) {
  bundle* tmp_b = nullptr;
  rpc_port_parcel_read_bundle(sub_parcel_.get(), &tmp_b);
  value = Bundle(tmp_b, false, true);

}

void Unit::Write(const RemoteException& value, rpc_port_parcel_h parcel) {
  auto cb = [&value, this](auto* p) {
    rpc_port_parcel_write_int32(p, value.GetCause());
    rpc_port_parcel_write_string(p, value.GetMessage().c_str());

  };

  if (parcel)
    cb(parcel);
  else
    cmds_.push_back(std::move(cb));
}

void Unit::Read(RemoteException& value) {
  char* tmp_str = nullptr;
  int cause = 0;
  std::string message;

  rpc_port_parcel_read_int32(sub_parcel_.get(), &cause);
  rpc_port_parcel_read_string(sub_parcel_.get(), &tmp_str);
  if (tmp_str != nullptr) {
    message = tmp_str;
    free(tmp_str);
  }

  value = RemoteException(cause, std::move(message));

}

void Unit::Write(const File& value, rpc_port_parcel_h parcel) {
  auto cb = [&value, this](auto* p) {
    rpc_port_parcel_write_string(p, value.GetFileName().c_str());

  };

  if (parcel)
    cb(parcel);
  else
    cmds_.push_back(std::move(cb));
}

void Unit::Read(File& value) {
  char* tmp_filename = nullptr;
  rpc_port_parcel_read_string(sub_parcel_.get(), &tmp_filename);
  if (tmp_filename != nullptr) {
    value = File(tmp_filename);
    free(tmp_filename);
  }

}

void Unit::Write(const TizenEntityReminder& value, rpc_port_parcel_h parcel) {
  auto cb = [&value, this](auto* p) {
    Write(value.GetId(), p);

    Write(value.GetExtra(), p);

    Write(value.GetTitle(), p);

    Write(value.GetDueDate(), p);

    Write(value.GetNote(), p);

    Write(value.GetCompleted(), p);

  };

  if (parcel)
    cb(parcel);
  else
    cmds_.push_back(std::move(cb));
}

void Unit::Read(TizenEntityReminder& value) {
  std::string tmp_Id;
  Read(tmp_Id);
  value.SetId(tmp_Id);

  std::string tmp_Extra;
  Read(tmp_Extra);
  value.SetExtra(tmp_Extra);

  std::string tmp_Title;
  Read(tmp_Title);
  value.SetTitle(tmp_Title);

  std::string tmp_DueDate;
  Read(tmp_DueDate);
  value.SetDueDate(tmp_DueDate);

  std::string tmp_Note;
  Read(tmp_Note);
  value.SetNote(tmp_Note);

  bool tmp_Completed = false;
  Read(tmp_Completed);
  value.SetCompleted(tmp_Completed);

}

void Unit::Write(const TizenEntityStatus& value, rpc_port_parcel_h parcel) {
  auto cb = [&value, this](auto* p) {
    Write(value.GetSuccess(), p);

    Write(value.GetReason(), p);

  };

  if (parcel)
    cb(parcel);
  else
    cmds_.push_back(std::move(cb));
}

void Unit::Read(TizenEntityStatus& value) {
  bool tmp_Success = false;
  Read(tmp_Success);
  value.SetSuccess(tmp_Success);

  std::string tmp_Reason;
  Read(tmp_Reason);
  value.SetReason(tmp_Reason);

}

void Unit::Write(const std::vector<TizenEntityReservation>& value, rpc_port_parcel_h parcel) {
  auto cb = [&value, this](auto* p) {
    rpc_port_parcel_write_array_count(p, static_cast<int>(value.size() & INT_MAX));

    for (auto& i : value)
      Write(i, p);

  };

  if (parcel)
    cb(parcel);
  else
    cmds_.push_back(std::move(cb));
}

void Unit::Read(std::vector<TizenEntityReservation>& value) {
  int tmp_size = 0;
  rpc_port_parcel_read_array_count(sub_parcel_.get(), &tmp_size);

  for (int index = 0; index < tmp_size; ++index) {
    TizenEntityReservation tmp_value;
    Read(tmp_value);
    value.push_back(tmp_value);
  }

}

void Unit::Write(const TizenEntityQuery& value, rpc_port_parcel_h parcel) {
  auto cb = [&value, this](auto* p) {
    Write(value.GetId(), p);

    Write(value.GetExtra(), p);

    Write(value.GetKeyword(), p);

    Write(value.GetCategory(), p);

    Write(value.GetNumber(), p);

  };

  if (parcel)
    cb(parcel);
  else
    cmds_.push_back(std::move(cb));
}

void Unit::Read(TizenEntityQuery& value) {
  std::string tmp_Id;
  Read(tmp_Id);
  value.SetId(tmp_Id);

  std::string tmp_Extra;
  Read(tmp_Extra);
  value.SetExtra(tmp_Extra);

  std::string tmp_Keyword;
  Read(tmp_Keyword);
  value.SetKeyword(tmp_Keyword);

  std::string tmp_Category;
  Read(tmp_Category);
  value.SetCategory(tmp_Category);

  int tmp_Number = 0;
  Read(tmp_Number);
  value.SetNumber(tmp_Number);

}

void Unit::Write(const TizenEntityChannel& value, rpc_port_parcel_h parcel) {
  auto cb = [&value, this](auto* p) {
    Write(value.GetId(), p);

    Write(value.GetExtra(), p);

    Write(value.GetMajor(), p);

    Write(value.GetMinor(), p);

    Write(value.GetName(), p);

    Write(value.GetServiceId(), p);

    Write(value.GetSource(), p);

    Write(value.GetSignal(), p);

  };

  if (parcel)
    cb(parcel);
  else
    cmds_.push_back(std::move(cb));
}

void Unit::Read(TizenEntityChannel& value) {
  std::string tmp_Id;
  Read(tmp_Id);
  value.SetId(tmp_Id);

  std::string tmp_Extra;
  Read(tmp_Extra);
  value.SetExtra(tmp_Extra);

  int tmp_Major = 0;
  Read(tmp_Major);
  value.SetMajor(tmp_Major);

  int tmp_Minor = 0;
  Read(tmp_Minor);
  value.SetMinor(tmp_Minor);

  std::string tmp_Name;
  Read(tmp_Name);
  value.SetName(tmp_Name);

  int tmp_ServiceId = 0;
  Read(tmp_ServiceId);
  value.SetServiceId(tmp_ServiceId);

  std::string tmp_Source;
  Read(tmp_Source);
  value.SetSource(tmp_Source);

  std::string tmp_Signal;
  Read(tmp_Signal);
  value.SetSignal(tmp_Signal);

}

void Unit::Write(const TizenEntityReservation& value, rpc_port_parcel_h parcel) {
  auto cb = [&value, this](auto* p) {
    Write(value.GetId(), p);

    Write(value.GetExtra(), p);

    Write(value.GetChannel(), p);

    Write(value.GetProgram(), p);

    Write(value.GetStartTime(), p);

    Write(value.GetEndTime(), p);

    Write(value.GetRepeat(), p);

    Write(value.GetKind(), p);

  };

  if (parcel)
    cb(parcel);
  else
    cmds_.push_back(std::move(cb));
}

void Unit::Read(TizenEntityReservation& value) {
  std::string tmp_Id;
  Read(tmp_Id);
  value.SetId(tmp_Id);

  std::string tmp_Extra;
  Read(tmp_Extra);
  value.SetExtra(tmp_Extra);

  TizenEntityChannel tmp_Channel;
  Read(tmp_Channel);
  value.SetChannel(tmp_Channel);

  TizenEntityProgram tmp_Program;
  Read(tmp_Program);
  value.SetProgram(tmp_Program);

  std::string tmp_StartTime;
  Read(tmp_StartTime);
  value.SetStartTime(tmp_StartTime);

  std::string tmp_EndTime;
  Read(tmp_EndTime);
  value.SetEndTime(tmp_EndTime);

  std::string tmp_Repeat;
  Read(tmp_Repeat);
  value.SetRepeat(tmp_Repeat);

  std::string tmp_Kind;
  Read(tmp_Kind);
  value.SetKind(tmp_Kind);

}

std::atomic<int> TizenActionSchedule::CallbackBase::seq_num_ { 0 };

TizenActionSchedule::CallbackBase::CallbackBase(int delegate_id, bool once) : id_(delegate_id), once_(once) {
  seq_id_ = seq_num_++;
}

int TizenActionSchedule::CallbackBase::GetId() const {
  return id_;
}

void TizenActionSchedule::CallbackBase::SetId(int id) {
  id_ = id;
}

int TizenActionSchedule::CallbackBase::GetSeqId() const {
  return seq_id_;
}

void TizenActionSchedule::CallbackBase::SetSeqId(int seq_id) {
  seq_id_ = seq_id;
}

bool TizenActionSchedule::CallbackBase::IsOnce() const {
  return once_;
}

void TizenActionSchedule::CallbackBase::SetOnce(bool once) {
  once_ = once;
}

std::string TizenActionSchedule::CallbackBase::GetTag() const {
  return std::to_string(id_) + "::" + std::to_string(seq_id_);
}

void TizenActionSchedule::CallbackBase::SetContext(void* context) {
  context_ = context;
}

void* TizenActionSchedule::CallbackBase::GetContext() const {
  return context_;
}

TizenActionSchedule::ServiceBase::ServiceBase(std::string sender, std::string instance)
: sender_(std::move(sender)),
instance_(std::move(instance)) {
  SetPrivilegeMap();

  dispatch_funcs_ = {
    { static_cast<int>(MethodId::AddRecording), std::bind(&TizenActionSchedule::ServiceBase::DispatchAddRecording, this, std::placeholders::_1, std::placeholders::_2, std::placeholders::_3, std::placeholders::_4) },
    { static_cast<int>(MethodId::AddViewing), std::bind(&TizenActionSchedule::ServiceBase::DispatchAddViewing, this, std::placeholders::_1, std::placeholders::_2, std::placeholders::_3, std::placeholders::_4) },
    { static_cast<int>(MethodId::CancelRecording), std::bind(&TizenActionSchedule::ServiceBase::DispatchCancelRecording, this, std::placeholders::_1, std::placeholders::_2, std::placeholders::_3, std::placeholders::_4) },
    { static_cast<int>(MethodId::CancelViewing), std::bind(&TizenActionSchedule::ServiceBase::DispatchCancelViewing, this, std::placeholders::_1, std::placeholders::_2, std::placeholders::_3, std::placeholders::_4) },
    { static_cast<int>(MethodId::CompleteReminder), std::bind(&TizenActionSchedule::ServiceBase::DispatchCompleteReminder, this, std::placeholders::_1, std::placeholders::_2, std::placeholders::_3, std::placeholders::_4) },
    { static_cast<int>(MethodId::CreateReminder), std::bind(&TizenActionSchedule::ServiceBase::DispatchCreateReminder, this, std::placeholders::_1, std::placeholders::_2, std::placeholders::_3, std::placeholders::_4) },
    { static_cast<int>(MethodId::DeleteReminder), std::bind(&TizenActionSchedule::ServiceBase::DispatchDeleteReminder, this, std::placeholders::_1, std::placeholders::_2, std::placeholders::_3, std::placeholders::_4) },
    { static_cast<int>(MethodId::GetReservations), std::bind(&TizenActionSchedule::ServiceBase::DispatchGetReservations, this, std::placeholders::_1, std::placeholders::_2, std::placeholders::_3, std::placeholders::_4) },
    { static_cast<int>(MethodId::SearchReminder), std::bind(&TizenActionSchedule::ServiceBase::DispatchSearchReminder, this, std::placeholders::_1, std::placeholders::_2, std::placeholders::_3, std::placeholders::_4) },
    { static_cast<int>(MethodId::UpdateReminder), std::bind(&TizenActionSchedule::ServiceBase::DispatchUpdateReminder, this, std::placeholders::_1, std::placeholders::_2, std::placeholders::_3, std::placeholders::_4) },
  };
}

void TizenActionSchedule::ServiceBase::SetPort(rpc_port_h port) {
  port_ = port;

}

void TizenActionSchedule::ServiceBase::Disconnect() {
  if (GetContext() != nullptr) {
    TizenActionSchedule_context_->Disconnect(GetContext());
    SetContext(nullptr);
  } else {
    int ret = rpc_port_disconnect(port_);
    if (ret != RPC_PORT_ERROR_NONE) {
      _E("Failed to disconnect the port. error(%d)", ret);
      return;
    }
  }

  instance_.clear();
  port_ = nullptr;
}

int TizenActionSchedule::ServiceBase::Dispatch(rpc_port_h port, rpc_port_h callback_port, rpc_port_parcel_h parcel, std::shared_ptr<ServiceBase> service) {
  return Dispatch(port, callback_port, parcel);

}

int TizenActionSchedule::ServiceBase::Dispatch(rpc_port_h port, rpc_port_h callback_port, rpc_port_parcel_h parcel) {
  rpc_port_parcel_header_h header;
  rpc_port_parcel_get_header(parcel, &header);

  int seq_num = -1;
  rpc_port_parcel_header_get_seq_num(header, &seq_num);

  UnitMap unit_map_;
  unit_map_.Deserialize(parcel);

  int cmd_ = -1;
  unit_map_.Read(1355467489 /*[METHOD]*/, cmd_);

  auto found = dispatch_funcs_.find(cmd_);
  if (found == dispatch_funcs_.end()) {
    _E("Unknown command(%d)", cmd_);
    rpc_port_parcel_destroy(parcel);
    return -1;
  }

  auto& func = found->second;
  func(port, callback_port, seq_num, unit_map_);
  rpc_port_parcel_destroy(parcel);
  return 0;
}

void TizenActionSchedule::ServiceBase::SetPrivilegeMap() {

}

void TizenActionSchedule::ServiceBase::SetParent(const TizenActionSchedule* parent) {
  parent_ = parent;
}

bool TizenActionSchedule::ServiceBase::CheckPrivileges(rpc_port_h port, int method_id) {
  int ret;
  uid_t uid;
  pid_t pid;
  auto found = privilege_map_.find(method_id);
  if (found == privilege_map_.end())
    return true;

  ret = dl_rpc_port_get_peer_info(port, &pid, &uid);
  if(ret == RPC_PORT_ERROR_NONE && uid < kRegularUidMin) {
    _W("Bypass access control. pid(%d), uid(%u)", pid, uid);
    return true;
  }

  for (const auto& privilege : found->second) {
    bool has = false;

    ret = dl_rpc_port_stub_has_privilege_local(
    parent_->GetRaw(), GetSender().c_str(), privilege.c_str(), &has);
    if (ret != 0 || !has) {
      return false;
    }
  }

  return true;
}

void TizenActionSchedule::ServiceBase::DispatchAddRecording(rpc_port_h port, rpc_port_h callback_port, int seq_num, const UnitMap& unit_map) {
  rpc_port_parcel_h parcel_;
  rpc_port_parcel_create(&parcel_);

  rpc_port_parcel_header_h header_;
  rpc_port_parcel_get_header(parcel_, &header_);
  rpc_port_parcel_header_set_seq_num(header_, seq_num);
  if (dl_rpc_port_parcel_header_set_tag_ex) {
    dl_rpc_port_parcel_header_set_tag_ex(header_, TIDL_VER_MAJOR,
    TIDL_VER_MINOR, TIDL_VER_PATCH, 2, RPC_PORT_PARCEL_HEADER_LAN_CPP);
  } else {
    rpc_port_parcel_header_set_tag(header_, TIDL_VERSION);
  }

  if (!CheckPrivileges(port, static_cast<int>(MethodId::AddRecording))) {
    _E("Permission denied");
    RemoteException remote_except(RPC_PORT_ERROR_PERMISSION_DENIED, "Permission denied");
    UnitMap()
    .Write(-1571313492 /*[REMOTE_EXCEPTION]*/, remote_except)
    .Write(1355467489 /*[METHOD]*/, static_cast<int>(MethodId::__Result))
    .Serialize(parcel_);
  } else {
    TizenEntityReservation reservation;
    unit_map.Read(-1563081780 /*reservation*/, reservation);

    try {
      auto ret_ = AddRecording(reservation);
      UnitMap()
      .Write(1497479973 /*[RESULT]*/, ret_)
      .Write(1355467489 /*[METHOD]*/, static_cast<int>(MethodId::__Result))
      .Serialize(parcel_);

      } catch (const RemoteException& e) {
      _E("Exception occurs. cause(%d), message(%s)", e.GetCause(), e.GetMessage().c_str());
      UnitMap()
      .Write(-1571313492 /*[REMOTE_EXCEPTION]*/, e)
      .Write(1355467489 /*[METHOD]*/, static_cast<int>(MethodId::__Result))
      .Serialize(parcel_);
    }
  }

  if (GetContext() != nullptr)
    TizenActionSchedule_context_->SendResult(GetContext(), parcel_);
  else
    rpc_port_parcel_send(parcel_, port);
  rpc_port_parcel_destroy(parcel_);
}

void TizenActionSchedule::ServiceBase::DispatchAddViewing(rpc_port_h port, rpc_port_h callback_port, int seq_num, const UnitMap& unit_map) {
  rpc_port_parcel_h parcel_;
  rpc_port_parcel_create(&parcel_);

  rpc_port_parcel_header_h header_;
  rpc_port_parcel_get_header(parcel_, &header_);
  rpc_port_parcel_header_set_seq_num(header_, seq_num);
  if (dl_rpc_port_parcel_header_set_tag_ex) {
    dl_rpc_port_parcel_header_set_tag_ex(header_, TIDL_VER_MAJOR,
    TIDL_VER_MINOR, TIDL_VER_PATCH, 2, RPC_PORT_PARCEL_HEADER_LAN_CPP);
  } else {
    rpc_port_parcel_header_set_tag(header_, TIDL_VERSION);
  }

  if (!CheckPrivileges(port, static_cast<int>(MethodId::AddViewing))) {
    _E("Permission denied");
    RemoteException remote_except(RPC_PORT_ERROR_PERMISSION_DENIED, "Permission denied");
    UnitMap()
    .Write(-1571313492 /*[REMOTE_EXCEPTION]*/, remote_except)
    .Write(1355467489 /*[METHOD]*/, static_cast<int>(MethodId::__Result))
    .Serialize(parcel_);
  } else {
    TizenEntityReservation reservation;
    unit_map.Read(-1563081780 /*reservation*/, reservation);

    try {
      auto ret_ = AddViewing(reservation);
      UnitMap()
      .Write(1497479973 /*[RESULT]*/, ret_)
      .Write(1355467489 /*[METHOD]*/, static_cast<int>(MethodId::__Result))
      .Serialize(parcel_);

      } catch (const RemoteException& e) {
      _E("Exception occurs. cause(%d), message(%s)", e.GetCause(), e.GetMessage().c_str());
      UnitMap()
      .Write(-1571313492 /*[REMOTE_EXCEPTION]*/, e)
      .Write(1355467489 /*[METHOD]*/, static_cast<int>(MethodId::__Result))
      .Serialize(parcel_);
    }
  }

  if (GetContext() != nullptr)
    TizenActionSchedule_context_->SendResult(GetContext(), parcel_);
  else
    rpc_port_parcel_send(parcel_, port);
  rpc_port_parcel_destroy(parcel_);
}

void TizenActionSchedule::ServiceBase::DispatchCancelRecording(rpc_port_h port, rpc_port_h callback_port, int seq_num, const UnitMap& unit_map) {
  rpc_port_parcel_h parcel_;
  rpc_port_parcel_create(&parcel_);

  rpc_port_parcel_header_h header_;
  rpc_port_parcel_get_header(parcel_, &header_);
  rpc_port_parcel_header_set_seq_num(header_, seq_num);
  if (dl_rpc_port_parcel_header_set_tag_ex) {
    dl_rpc_port_parcel_header_set_tag_ex(header_, TIDL_VER_MAJOR,
    TIDL_VER_MINOR, TIDL_VER_PATCH, 2, RPC_PORT_PARCEL_HEADER_LAN_CPP);
  } else {
    rpc_port_parcel_header_set_tag(header_, TIDL_VERSION);
  }

  if (!CheckPrivileges(port, static_cast<int>(MethodId::CancelRecording))) {
    _E("Permission denied");
    RemoteException remote_except(RPC_PORT_ERROR_PERMISSION_DENIED, "Permission denied");
    UnitMap()
    .Write(-1571313492 /*[REMOTE_EXCEPTION]*/, remote_except)
    .Write(1355467489 /*[METHOD]*/, static_cast<int>(MethodId::__Result))
    .Serialize(parcel_);
  } else {
    TizenEntityReservation reservation;
    unit_map.Read(-1563081780 /*reservation*/, reservation);

    try {
      auto ret_ = CancelRecording(reservation);
      UnitMap()
      .Write(1497479973 /*[RESULT]*/, ret_)
      .Write(1355467489 /*[METHOD]*/, static_cast<int>(MethodId::__Result))
      .Serialize(parcel_);

      } catch (const RemoteException& e) {
      _E("Exception occurs. cause(%d), message(%s)", e.GetCause(), e.GetMessage().c_str());
      UnitMap()
      .Write(-1571313492 /*[REMOTE_EXCEPTION]*/, e)
      .Write(1355467489 /*[METHOD]*/, static_cast<int>(MethodId::__Result))
      .Serialize(parcel_);
    }
  }

  if (GetContext() != nullptr)
    TizenActionSchedule_context_->SendResult(GetContext(), parcel_);
  else
    rpc_port_parcel_send(parcel_, port);
  rpc_port_parcel_destroy(parcel_);
}

void TizenActionSchedule::ServiceBase::DispatchCancelViewing(rpc_port_h port, rpc_port_h callback_port, int seq_num, const UnitMap& unit_map) {
  rpc_port_parcel_h parcel_;
  rpc_port_parcel_create(&parcel_);

  rpc_port_parcel_header_h header_;
  rpc_port_parcel_get_header(parcel_, &header_);
  rpc_port_parcel_header_set_seq_num(header_, seq_num);
  if (dl_rpc_port_parcel_header_set_tag_ex) {
    dl_rpc_port_parcel_header_set_tag_ex(header_, TIDL_VER_MAJOR,
    TIDL_VER_MINOR, TIDL_VER_PATCH, 2, RPC_PORT_PARCEL_HEADER_LAN_CPP);
  } else {
    rpc_port_parcel_header_set_tag(header_, TIDL_VERSION);
  }

  if (!CheckPrivileges(port, static_cast<int>(MethodId::CancelViewing))) {
    _E("Permission denied");
    RemoteException remote_except(RPC_PORT_ERROR_PERMISSION_DENIED, "Permission denied");
    UnitMap()
    .Write(-1571313492 /*[REMOTE_EXCEPTION]*/, remote_except)
    .Write(1355467489 /*[METHOD]*/, static_cast<int>(MethodId::__Result))
    .Serialize(parcel_);
  } else {
    TizenEntityReservation reservation;
    unit_map.Read(-1563081780 /*reservation*/, reservation);

    try {
      auto ret_ = CancelViewing(reservation);
      UnitMap()
      .Write(1497479973 /*[RESULT]*/, ret_)
      .Write(1355467489 /*[METHOD]*/, static_cast<int>(MethodId::__Result))
      .Serialize(parcel_);

      } catch (const RemoteException& e) {
      _E("Exception occurs. cause(%d), message(%s)", e.GetCause(), e.GetMessage().c_str());
      UnitMap()
      .Write(-1571313492 /*[REMOTE_EXCEPTION]*/, e)
      .Write(1355467489 /*[METHOD]*/, static_cast<int>(MethodId::__Result))
      .Serialize(parcel_);
    }
  }

  if (GetContext() != nullptr)
    TizenActionSchedule_context_->SendResult(GetContext(), parcel_);
  else
    rpc_port_parcel_send(parcel_, port);
  rpc_port_parcel_destroy(parcel_);
}

void TizenActionSchedule::ServiceBase::DispatchCompleteReminder(rpc_port_h port, rpc_port_h callback_port, int seq_num, const UnitMap& unit_map) {
  rpc_port_parcel_h parcel_;
  rpc_port_parcel_create(&parcel_);

  rpc_port_parcel_header_h header_;
  rpc_port_parcel_get_header(parcel_, &header_);
  rpc_port_parcel_header_set_seq_num(header_, seq_num);
  if (dl_rpc_port_parcel_header_set_tag_ex) {
    dl_rpc_port_parcel_header_set_tag_ex(header_, TIDL_VER_MAJOR,
    TIDL_VER_MINOR, TIDL_VER_PATCH, 2, RPC_PORT_PARCEL_HEADER_LAN_CPP);
  } else {
    rpc_port_parcel_header_set_tag(header_, TIDL_VERSION);
  }

  if (!CheckPrivileges(port, static_cast<int>(MethodId::CompleteReminder))) {
    _E("Permission denied");
    RemoteException remote_except(RPC_PORT_ERROR_PERMISSION_DENIED, "Permission denied");
    UnitMap()
    .Write(-1571313492 /*[REMOTE_EXCEPTION]*/, remote_except)
    .Write(1355467489 /*[METHOD]*/, static_cast<int>(MethodId::__Result))
    .Serialize(parcel_);
  } else {
    TizenEntityReminder reminder;
    unit_map.Read(-518602638 /*reminder*/, reminder);

    try {
      auto ret_ = CompleteReminder(reminder);
      UnitMap()
      .Write(1497479973 /*[RESULT]*/, ret_)
      .Write(1355467489 /*[METHOD]*/, static_cast<int>(MethodId::__Result))
      .Serialize(parcel_);

      } catch (const RemoteException& e) {
      _E("Exception occurs. cause(%d), message(%s)", e.GetCause(), e.GetMessage().c_str());
      UnitMap()
      .Write(-1571313492 /*[REMOTE_EXCEPTION]*/, e)
      .Write(1355467489 /*[METHOD]*/, static_cast<int>(MethodId::__Result))
      .Serialize(parcel_);
    }
  }

  if (GetContext() != nullptr)
    TizenActionSchedule_context_->SendResult(GetContext(), parcel_);
  else
    rpc_port_parcel_send(parcel_, port);
  rpc_port_parcel_destroy(parcel_);
}

void TizenActionSchedule::ServiceBase::DispatchCreateReminder(rpc_port_h port, rpc_port_h callback_port, int seq_num, const UnitMap& unit_map) {
  rpc_port_parcel_h parcel_;
  rpc_port_parcel_create(&parcel_);

  rpc_port_parcel_header_h header_;
  rpc_port_parcel_get_header(parcel_, &header_);
  rpc_port_parcel_header_set_seq_num(header_, seq_num);
  if (dl_rpc_port_parcel_header_set_tag_ex) {
    dl_rpc_port_parcel_header_set_tag_ex(header_, TIDL_VER_MAJOR,
    TIDL_VER_MINOR, TIDL_VER_PATCH, 2, RPC_PORT_PARCEL_HEADER_LAN_CPP);
  } else {
    rpc_port_parcel_header_set_tag(header_, TIDL_VERSION);
  }

  if (!CheckPrivileges(port, static_cast<int>(MethodId::CreateReminder))) {
    _E("Permission denied");
    RemoteException remote_except(RPC_PORT_ERROR_PERMISSION_DENIED, "Permission denied");
    UnitMap()
    .Write(-1571313492 /*[REMOTE_EXCEPTION]*/, remote_except)
    .Write(1355467489 /*[METHOD]*/, static_cast<int>(MethodId::__Result))
    .Serialize(parcel_);
  } else {
    TizenEntityReminder reminder;
    unit_map.Read(-518602638 /*reminder*/, reminder);

    try {
      auto ret_ = CreateReminder(reminder);
      UnitMap()
      .Write(1497479973 /*[RESULT]*/, ret_)
      .Write(1355467489 /*[METHOD]*/, static_cast<int>(MethodId::__Result))
      .Serialize(parcel_);

      } catch (const RemoteException& e) {
      _E("Exception occurs. cause(%d), message(%s)", e.GetCause(), e.GetMessage().c_str());
      UnitMap()
      .Write(-1571313492 /*[REMOTE_EXCEPTION]*/, e)
      .Write(1355467489 /*[METHOD]*/, static_cast<int>(MethodId::__Result))
      .Serialize(parcel_);
    }
  }

  if (GetContext() != nullptr)
    TizenActionSchedule_context_->SendResult(GetContext(), parcel_);
  else
    rpc_port_parcel_send(parcel_, port);
  rpc_port_parcel_destroy(parcel_);
}

void TizenActionSchedule::ServiceBase::DispatchDeleteReminder(rpc_port_h port, rpc_port_h callback_port, int seq_num, const UnitMap& unit_map) {
  rpc_port_parcel_h parcel_;
  rpc_port_parcel_create(&parcel_);

  rpc_port_parcel_header_h header_;
  rpc_port_parcel_get_header(parcel_, &header_);
  rpc_port_parcel_header_set_seq_num(header_, seq_num);
  if (dl_rpc_port_parcel_header_set_tag_ex) {
    dl_rpc_port_parcel_header_set_tag_ex(header_, TIDL_VER_MAJOR,
    TIDL_VER_MINOR, TIDL_VER_PATCH, 2, RPC_PORT_PARCEL_HEADER_LAN_CPP);
  } else {
    rpc_port_parcel_header_set_tag(header_, TIDL_VERSION);
  }

  if (!CheckPrivileges(port, static_cast<int>(MethodId::DeleteReminder))) {
    _E("Permission denied");
    RemoteException remote_except(RPC_PORT_ERROR_PERMISSION_DENIED, "Permission denied");
    UnitMap()
    .Write(-1571313492 /*[REMOTE_EXCEPTION]*/, remote_except)
    .Write(1355467489 /*[METHOD]*/, static_cast<int>(MethodId::__Result))
    .Serialize(parcel_);
  } else {
    TizenEntityReminder reminder;
    unit_map.Read(-518602638 /*reminder*/, reminder);

    try {
      auto ret_ = DeleteReminder(reminder);
      UnitMap()
      .Write(1497479973 /*[RESULT]*/, ret_)
      .Write(1355467489 /*[METHOD]*/, static_cast<int>(MethodId::__Result))
      .Serialize(parcel_);

      } catch (const RemoteException& e) {
      _E("Exception occurs. cause(%d), message(%s)", e.GetCause(), e.GetMessage().c_str());
      UnitMap()
      .Write(-1571313492 /*[REMOTE_EXCEPTION]*/, e)
      .Write(1355467489 /*[METHOD]*/, static_cast<int>(MethodId::__Result))
      .Serialize(parcel_);
    }
  }

  if (GetContext() != nullptr)
    TizenActionSchedule_context_->SendResult(GetContext(), parcel_);
  else
    rpc_port_parcel_send(parcel_, port);
  rpc_port_parcel_destroy(parcel_);
}

void TizenActionSchedule::ServiceBase::DispatchGetReservations(rpc_port_h port, rpc_port_h callback_port, int seq_num, const UnitMap& unit_map) {
  rpc_port_parcel_h parcel_;
  rpc_port_parcel_create(&parcel_);

  rpc_port_parcel_header_h header_;
  rpc_port_parcel_get_header(parcel_, &header_);
  rpc_port_parcel_header_set_seq_num(header_, seq_num);
  if (dl_rpc_port_parcel_header_set_tag_ex) {
    dl_rpc_port_parcel_header_set_tag_ex(header_, TIDL_VER_MAJOR,
    TIDL_VER_MINOR, TIDL_VER_PATCH, 2, RPC_PORT_PARCEL_HEADER_LAN_CPP);
  } else {
    rpc_port_parcel_header_set_tag(header_, TIDL_VERSION);
  }

  if (!CheckPrivileges(port, static_cast<int>(MethodId::GetReservations))) {
    _E("Permission denied");
    RemoteException remote_except(RPC_PORT_ERROR_PERMISSION_DENIED, "Permission denied");
    UnitMap()
    .Write(-1571313492 /*[REMOTE_EXCEPTION]*/, remote_except)
    .Write(1355467489 /*[METHOD]*/, static_cast<int>(MethodId::__Result))
    .Serialize(parcel_);
  } else {
    std::vector<TizenEntityReservation> result;

    try {
      auto ret_ = GetReservations(result);
      UnitMap()
      .Write(1497479973 /*[RESULT]*/, ret_)
      .Write(-934426595 /*result*/, result)
      .Write(1355467489 /*[METHOD]*/, static_cast<int>(MethodId::__Result))
      .Serialize(parcel_);

      } catch (const RemoteException& e) {
      _E("Exception occurs. cause(%d), message(%s)", e.GetCause(), e.GetMessage().c_str());
      UnitMap()
      .Write(-1571313492 /*[REMOTE_EXCEPTION]*/, e)
      .Write(1355467489 /*[METHOD]*/, static_cast<int>(MethodId::__Result))
      .Serialize(parcel_);
    }
  }

  if (GetContext() != nullptr)
    TizenActionSchedule_context_->SendResult(GetContext(), parcel_);
  else
    rpc_port_parcel_send(parcel_, port);
  rpc_port_parcel_destroy(parcel_);
}

void TizenActionSchedule::ServiceBase::DispatchSearchReminder(rpc_port_h port, rpc_port_h callback_port, int seq_num, const UnitMap& unit_map) {
  rpc_port_parcel_h parcel_;
  rpc_port_parcel_create(&parcel_);

  rpc_port_parcel_header_h header_;
  rpc_port_parcel_get_header(parcel_, &header_);
  rpc_port_parcel_header_set_seq_num(header_, seq_num);
  if (dl_rpc_port_parcel_header_set_tag_ex) {
    dl_rpc_port_parcel_header_set_tag_ex(header_, TIDL_VER_MAJOR,
    TIDL_VER_MINOR, TIDL_VER_PATCH, 2, RPC_PORT_PARCEL_HEADER_LAN_CPP);
  } else {
    rpc_port_parcel_header_set_tag(header_, TIDL_VERSION);
  }

  if (!CheckPrivileges(port, static_cast<int>(MethodId::SearchReminder))) {
    _E("Permission denied");
    RemoteException remote_except(RPC_PORT_ERROR_PERMISSION_DENIED, "Permission denied");
    UnitMap()
    .Write(-1571313492 /*[REMOTE_EXCEPTION]*/, remote_except)
    .Write(1355467489 /*[METHOD]*/, static_cast<int>(MethodId::__Result))
    .Serialize(parcel_);
  } else {
    TizenEntityQuery query;
    unit_map.Read(107944136 /*query*/, query);

    std::vector<TizenEntityReminder> result;

    try {
      auto ret_ = SearchReminder(query, result);
      UnitMap()
      .Write(1497479973 /*[RESULT]*/, ret_)
      .Write(-934426595 /*result*/, result)
      .Write(1355467489 /*[METHOD]*/, static_cast<int>(MethodId::__Result))
      .Serialize(parcel_);

      } catch (const RemoteException& e) {
      _E("Exception occurs. cause(%d), message(%s)", e.GetCause(), e.GetMessage().c_str());
      UnitMap()
      .Write(-1571313492 /*[REMOTE_EXCEPTION]*/, e)
      .Write(1355467489 /*[METHOD]*/, static_cast<int>(MethodId::__Result))
      .Serialize(parcel_);
    }
  }

  if (GetContext() != nullptr)
    TizenActionSchedule_context_->SendResult(GetContext(), parcel_);
  else
    rpc_port_parcel_send(parcel_, port);
  rpc_port_parcel_destroy(parcel_);
}

void TizenActionSchedule::ServiceBase::DispatchUpdateReminder(rpc_port_h port, rpc_port_h callback_port, int seq_num, const UnitMap& unit_map) {
  rpc_port_parcel_h parcel_;
  rpc_port_parcel_create(&parcel_);

  rpc_port_parcel_header_h header_;
  rpc_port_parcel_get_header(parcel_, &header_);
  rpc_port_parcel_header_set_seq_num(header_, seq_num);
  if (dl_rpc_port_parcel_header_set_tag_ex) {
    dl_rpc_port_parcel_header_set_tag_ex(header_, TIDL_VER_MAJOR,
    TIDL_VER_MINOR, TIDL_VER_PATCH, 2, RPC_PORT_PARCEL_HEADER_LAN_CPP);
  } else {
    rpc_port_parcel_header_set_tag(header_, TIDL_VERSION);
  }

  if (!CheckPrivileges(port, static_cast<int>(MethodId::UpdateReminder))) {
    _E("Permission denied");
    RemoteException remote_except(RPC_PORT_ERROR_PERMISSION_DENIED, "Permission denied");
    UnitMap()
    .Write(-1571313492 /*[REMOTE_EXCEPTION]*/, remote_except)
    .Write(1355467489 /*[METHOD]*/, static_cast<int>(MethodId::__Result))
    .Serialize(parcel_);
  } else {
    TizenEntityReminder reminder;
    unit_map.Read(-518602638 /*reminder*/, reminder);

    try {
      auto ret_ = UpdateReminder(reminder);
      UnitMap()
      .Write(1497479973 /*[RESULT]*/, ret_)
      .Write(1355467489 /*[METHOD]*/, static_cast<int>(MethodId::__Result))
      .Serialize(parcel_);

      } catch (const RemoteException& e) {
      _E("Exception occurs. cause(%d), message(%s)", e.GetCause(), e.GetMessage().c_str());
      UnitMap()
      .Write(-1571313492 /*[REMOTE_EXCEPTION]*/, e)
      .Write(1355467489 /*[METHOD]*/, static_cast<int>(MethodId::__Result))
      .Serialize(parcel_);
    }
  }

  if (GetContext() != nullptr)
    TizenActionSchedule_context_->SendResult(GetContext(), parcel_);
  else
    rpc_port_parcel_send(parcel_, port);
  rpc_port_parcel_destroy(parcel_);
}

void TizenActionSchedule::ServiceBase::SetContext(void* context) {
  context_ = context;
}

void* TizenActionSchedule::ServiceBase::GetContext() const {
  return context_;
}

TizenActionSchedule::TizenActionSchedule() {
  _W("TizenActionSchedule ctor");
  int ret = rpc_port_stub_create(&stub_, "TizenActionSchedule");
  if (ret != RPC_PORT_ERROR_NONE) {
    _E("Failed to create stub. error(%d)", ret);
    throw InvalidIOException();
  }
  rpc_port_stub_add_connected_event_cb(stub_, OnConnectedCb, this);
  rpc_port_stub_add_disconnected_event_cb(stub_, OnDisconnectedCb, this);
  rpc_port_stub_add_received_event_cb(stub_, OnReceivedCb, this);

  TizenActionSchedule_context_ = std::make_unique<LocalExecution>("TizenActionSchedule", this);
}

TizenActionSchedule::~TizenActionSchedule() {
  _W("TizenActionSchedule dtor");
  for (auto& service : services_) {
    if(!service->GetInstance().empty())
    service->OnTerminate();

    if (TizenActionSchedule_context_ && service->GetContext())
      TizenActionSchedule_context_->Disconnect(service->GetContext());
  }

  TizenActionSchedule_context_.reset();
  if (stub_ != nullptr)
    rpc_port_stub_destroy(stub_);
}

void TizenActionSchedule::Listen(std::shared_ptr<TizenActionSchedule::ServiceBase::Factory> service_factory) {
  service_factory_ = std::move(service_factory);
  int ret = rpc_port_stub_listen(stub_);
  if (ret != RPC_PORT_ERROR_NONE) {
    _E("Failed to listen stub. error(%d)", ret);
    if (ret == RPC_PORT_ERROR_INVALID_PARAMETER || ret == RPC_PORT_ERROR_IO_ERROR)
      throw InvalidIOException();
  }

  TizenActionSchedule_context_->SetListening(true);
}
void TizenActionSchedule::OnConnectedCb(const char* sender, const char* instance, void* user_data) {
  auto* handle = static_cast<TizenActionSchedule*>(user_data);
  auto service = handle->service_factory_->CreateService(sender, instance);

  service->SetParent(handle);
  rpc_port_h port;
  int ret = rpc_port_stub_get_port(handle->stub_, RPC_PORT_PORT_CALLBACK, instance, &port);
  if (ret != RPC_PORT_ERROR_NONE) {
    _E("Failed to get port. error(%d)", ret);
    return;
  }

  service->SetPort(port);
  service->OnCreate();
  handle->services_.emplace_back(std::move(service));
}

void TizenActionSchedule::OnDisconnectedCb(const char* sender, const char* instance, void* user_data) {
  auto* handle = static_cast<TizenActionSchedule*>(user_data);
  auto iter = handle->services_.begin();
  while (iter != handle->services_.end()) {
    if ((*iter)->GetInstance() == instance) {
      (*iter)->OnTerminate();
      iter = handle->services_.erase(iter);
      break;
    }

    iter++;
  }
}

int TizenActionSchedule::OnReceivedCb(const char* sender, const char* instance, rpc_port_h port, void* user_data) {
  auto* handle = static_cast<TizenActionSchedule*>(user_data);
  std::shared_ptr<ServiceBase> service;
  for (auto& iter : handle->services_) {
    if (iter->GetInstance() == instance) {
      service = iter;
      break;
    }
  }

  if (service.get() == nullptr) {
    _E("Failed to find TizenActionSchedule context. instance(%s)", instance);
    return -1;
  }

  rpc_port_h callback_port;
  int ret = rpc_port_stub_get_port(handle->stub_, RPC_PORT_PORT_CALLBACK, instance, &callback_port);
  if (ret != 0) {
    _E("Failed to get callback port. error(%d)", ret);
    return -1;
  }

  rpc_port_parcel_h parcel;
  ret = rpc_port_parcel_create_from_port(&parcel, port);
  if (ret != 0) {
    _E("Failed to create parcel from port. error(%d)", ret);
    return ret;
  }

  return service->Dispatch(port, callback_port, parcel, service);
}

void TizenActionSchedule::OnLocalConnected(void* context, const std::string& sender, const std::string& instance, bool sync) {
  auto service = service_factory_->CreateService(sender, instance);
  service->SetParent(this);
  service->SetContext(context);
  service->OnCreate();
  services_.emplace_back(std::move(service));
  TizenActionSchedule_context_->Connect(context, sync);
}

void TizenActionSchedule::OnLocalDisconnected(void* context, const std::string& sender, const std::string& instance) {
  auto iter = services_.begin();
  while (iter != services_.end()) {
    if ((*iter)->GetInstance() == instance) {
      (*iter)->OnTerminate();
      iter = services_.erase(iter);
      break;
    }

    iter++;
  }

  TizenActionSchedule_context_->Disconnect(context);
}

void TizenActionSchedule::OnLocalReceived(void* context, rpc_port_parcel_h parcel) {
  std::shared_ptr<ServiceBase> service;
  for (auto& iter : services_) {
    if (iter->GetContext() == context) {
      service = iter;
      break;
    }
  }

  if (service.get() == nullptr) {
    _E("Failed to find TizenActionSchedule context. context(%p)", context);
    return;
  }

  service->Dispatch(nullptr, nullptr, parcel, service);
}

}  // namespace stub
}  // namespace schedule_action_provider
}  // namespace rpc_port

EXPORT_API int rpc_port_stub_tizen_action_schedule_lem_TizenActionSchedule_connect(void* context, const char* sender, const char* instance, bool sync) {
  if (TizenActionSchedule_context_.get() == nullptr || !TizenActionSchedule_context_->IsListening()) {
    _E("Server is not ready");
    return RPC_PORT_ERROR_IO_ERROR;
  }

  std::string sender_str(sender);
  std::string instance_str(instance);
  if (gettid() == getpid()) {
    TizenActionSchedule_context_->OnConnected(context, sender, instance, sync);
    return RPC_PORT_ERROR_NONE;
  }

  auto* func = new std::function<void()>([context, sender_str, instance_str, sync] {
    TizenActionSchedule_context_->OnConnected(context, sender_str, instance_str, sync);
  });
  if (!IdleAddOnce(TizenActionSchedule_context_->GetContext(), func)) {
    delete func;
    return RPC_PORT_ERROR_OUT_OF_MEMORY;
  }

  return RPC_PORT_ERROR_NONE;
}

EXPORT_API int rpc_port_stub_tizen_action_schedule_lem_TizenActionSchedule_disconnect(void* context, const char* sender, const char* instance) {
  if (TizenActionSchedule_context_.get() == nullptr || !TizenActionSchedule_context_->IsListening()) {
    _E("Server is not ready");
    return RPC_PORT_ERROR_IO_ERROR;
  }

  std::string sender_str(sender);
  std::string instance_str(instance);
  if (gettid() == getpid()) {
    TizenActionSchedule_context_->OnDisconnected(context, sender, instance);
    return RPC_PORT_ERROR_NONE;
  }

  auto* func = new std::function<void()>([context, sender_str, instance_str] {
    TizenActionSchedule_context_->OnDisconnected(context, sender_str, instance_str);
  });
  if (!IdleAddOnce(TizenActionSchedule_context_->GetContext(), func)) {
    delete func;
    return RPC_PORT_ERROR_OUT_OF_MEMORY;
  }

  return RPC_PORT_ERROR_NONE;
}

EXPORT_API int rpc_port_stub_tizen_action_schedule_lem_TizenActionSchedule_send(void* context, rpc_port_parcel_h parcel) {
  if (TizenActionSchedule_context_.get() == nullptr || !TizenActionSchedule_context_->IsListening()) {
    _E("Server is not ready");
    return RPC_PORT_ERROR_IO_ERROR;
  }

  rpc_port_parcel_h cloned_parcel = nullptr;
  dl_rpc_port_parcel_clone(&cloned_parcel, parcel);
  if (gettid() == getpid()) {
    TizenActionSchedule_context_->OnReceived(context, cloned_parcel);
    return RPC_PORT_ERROR_NONE;
  }

  auto* func = new std::function<void()>([context, cloned_parcel] {
    TizenActionSchedule_context_->OnReceived(context, cloned_parcel);
  });
  if (!IdleAddOnce(TizenActionSchedule_context_->GetContext(), func)) {
    delete func;
    return RPC_PORT_ERROR_OUT_OF_MEMORY;
  }

  return RPC_PORT_ERROR_NONE;
}

