<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Tizen.NET" Version="10.0.0.17508" />
    <ProjectReference Include="../PhotoGallery.Domain/PhotoGallery.Domain.csproj" />
    <ProjectReference Include="../PhotoGallery.UseCases/PhotoGallery.UseCases.csproj" />
  </ItemGroup>
</Project>
