<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="../../actions/*.action" Link="res/%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
    <Compile Include="../../../Shared/ViewAnnotations/NuiViewAnnotations.cs" Link="NuiViewAnnotations.cs" />
    <PackageReference Include="Tizen.NET" Version="14.0.0.19326" />
    <ProjectReference Include="../PhotoGallery.Domain/PhotoGallery.Domain.csproj" />
    <ProjectReference Include="../PhotoGallery.Persistence/PhotoGallery.Persistence.csproj" />
    <ProjectReference Include="../PhotoGallery.UseCases/PhotoGallery.UseCases.csproj" />
    <ProjectReference Include="../PhotoGallery.ActionProvider/PhotoGallery.ActionProvider.csproj" />
    <ProjectReference Include="../PhotoGallery.ViewActionProvider/PhotoGallery.ViewActionProvider.csproj" />
  </ItemGroup>
</Project>
