using RPCPort.ViewActions;
using RPCPort.ViewActions.Stub;

namespace DisplayPresentation.ViewActionProvider;

/// <summary>
/// Typed View routes over the lock-protected snapshot of currently rendered NUI content.
/// The registry never turns an arbitrary caller-supplied View into a Presentation.
/// </summary>
public sealed class DisplayPresentationViewService : TizenInternalActionView.ServiceBase
{
    public override void OnCreate()
    {
    }

    public override void OnTerminate()
    {
    }

    public override TizenEntityStatus FindById(string id, out TizenEntityView v)
    {
        if (string.IsNullOrWhiteSpace(id))
        {
            v = EmptyView();
            return Failure("A view ID is required.");
        }

        return DisplayPresentationViewProviderState.TryFind(id, out v)
            ? Success()
            : Failure("The requested presentation view is not currently visible.");
    }

    public override TizenEntityStatus GetAnnotatedViews(out List<TizenEntityView> views)
    {
        views = DisplayPresentationViewProviderState.GetAnnotatedViews();
        return Success();
    }

    public override TizenEntityStatus GetFocusedView(out TizenEntityView v)
    {
        return DisplayPresentationViewProviderState.TryGetFocused(out v)
            ? Success()
            : Failure("No annotated presentation view is currently focused.");
    }

    public override TizenEntityStatus ToPresentation(TizenEntityView view, out TizenEntityPresentation result)
    {
        if (view?.Annotation is null ||
            !DisplayPresentationViewProviderState.TryGetPresentation(view.Id, view.Annotation.EntityInfo, out var presentation))
        {
            result = new TizenEntityPresentation { Template = string.Empty, Document = string.Empty };
            return Failure("A current DisplayPresentation ViewAnnotation is required.");
        }

        result = new TizenEntityPresentation { Template = presentation.Template, Document = presentation.Document };
        return Success();
    }

    private static TizenEntityView EmptyView() => new()
    {
        Id = string.Empty,
        Extra = string.Empty,
        Type = string.Empty,
        Description = string.Empty,
        ScreenBounds = new ScreenBounds(),
        WindowBounds = new WindowBounds(),
        Annotation = new Annotation { EntityType = string.Empty, EntityId = string.Empty, EntityInfo = string.Empty },
    };

    private static TizenEntityStatus Success() => new() { Success = true, Reason = string.Empty };

    private static TizenEntityStatus Failure(string reason) => new() { Success = false, Reason = reason };
}

/// <summary>
/// The NUI app publishes only after it obtains finite, positive screen geometry. The stored
/// Presentation entity snapshot is generated by its owning Action binding, not hand-serialized.
/// </summary>
internal static class DisplayPresentationViewProviderState
{
    internal const string PresentationEntityType = "Tizen.Entity.Presentation";
    private static readonly object Gate = new();
    private static IReadOnlyList<PublishedPresentationView> _visibleViews = [];

    internal static void Publish(PublishedPresentationView view)
    {
        ArgumentNullException.ThrowIfNull(view);
        if (!IsValid(view.ScreenX, view.ScreenY, view.Width, view.Height))
        {
            Clear();
            return;
        }

        lock (Gate)
        {
            _visibleViews = [view];
        }
    }

    internal static void Clear()
    {
        lock (Gate)
        {
            _visibleViews = [];
        }
    }

    internal static bool TryFind(string id, out TizenEntityView view)
    {
        lock (Gate)
        {
            var snapshot = _visibleViews.FirstOrDefault(candidate => candidate.ViewId == id);
            view = snapshot is null ? EmptyView() : ToAnnotatedView(snapshot);
            return snapshot is not null;
        }
    }

    internal static List<TizenEntityView> GetAnnotatedViews()
    {
        lock (Gate)
        {
            return _visibleViews.Select(ToAnnotatedView).ToList();
        }
    }

    internal static bool TryGetFocused(out TizenEntityView view)
    {
        lock (Gate)
        {
            var snapshot = _visibleViews.FirstOrDefault(candidate => candidate.IsFocused);
            view = snapshot is null ? EmptyView() : ToAnnotatedView(snapshot);
            return snapshot is not null;
        }
    }

    internal static bool TryGetPresentation(string viewId, string entityInfo, out PublishedPresentationView presentation)
    {
        lock (Gate)
        {
            presentation = _visibleViews.FirstOrDefault(candidate =>
                candidate.ViewId == viewId && candidate.EntityInfo == entityInfo);
            return presentation is not null;
        }
    }

    private static TizenEntityView ToAnnotatedView(PublishedPresentationView snapshot) => new()
    {
        Id = snapshot.ViewId,
        Extra = string.Empty,
        Type = "DisplayPresentation.Surface",
        Description = "Current bounded A2UI presentation surface",
        ScreenBounds = new ScreenBounds { X = snapshot.ScreenX, Y = snapshot.ScreenY, Width = snapshot.Width, Height = snapshot.Height },
        WindowBounds = snapshot.WindowX is { } windowX && snapshot.WindowY is { } windowY
            ? new WindowBounds { X = windowX, Y = windowY, Width = snapshot.Width, Height = snapshot.Height }
            : null,
        IsFocused = snapshot.IsFocused,
        IsEnabled = true,
        Annotation = new Annotation
        {
            EntityType = PresentationEntityType,
            EntityId = snapshot.SurfaceId,
            EntityInfo = snapshot.EntityInfo,
        },
    };

    private static TizenEntityView EmptyView() => new()
    {
        Id = string.Empty,
        Extra = string.Empty,
        Type = string.Empty,
        Description = string.Empty,
        ScreenBounds = new ScreenBounds(),
        WindowBounds = new WindowBounds(),
        Annotation = new Annotation { EntityType = string.Empty, EntityId = string.Empty, EntityInfo = string.Empty },
    };

    private static bool IsValid(double x, double y, double width, double height) =>
        double.IsFinite(x) && double.IsFinite(y) && double.IsFinite(width) && double.IsFinite(height) && width > 0 && height > 0;

    internal sealed record PublishedPresentationView(
        string ViewId,
        string SurfaceId,
        string Template,
        string Document,
        string EntityInfo,
        double ScreenX,
        double ScreenY,
        double? WindowX,
        double? WindowY,
        double Width,
        double Height,
        bool IsFocused);
}
