
/*
 * Generated by tidlc 2.9.1.
 */

using System;
using System.Collections.Generic;
using System.Collections.Concurrent;
using System.Threading;
using System.Reflection;
using Tizen.Applications;
using Tizen.Applications.RPCPort;

namespace RPCPort
{
    namespace TizenInternalActionView
    {
        internal class LocalExecution
        {
            object _instance = null;
            MethodInfo _send_result = null;
            MethodInfo _send_request = null;
            MethodInfo _disconnect = null;

            internal bool _online = false;

            internal LocalExecution (object instance)
            {
                Type type = instance.GetType();

                if (type == null)
                    return;

                _send_result = type.GetMethod("OnLemResultEvent", BindingFlags.NonPublic | BindingFlags.Instance);
                if (_send_result == null) { return; }

                _send_request = type.GetMethod("OnLemReceivedEvent", BindingFlags.NonPublic | BindingFlags.Instance);

                _disconnect = type.GetMethod("OnLemDisconnectedEvent", BindingFlags.NonPublic | BindingFlags.Instance);
                if (_disconnect == null) { return; }

                _instance = instance;
                _online = true;

            }

            internal void SendResult(Parcel result)
            {
                _send_result.Invoke(_instance, new object[] {result});
            }

            internal void SendRequest(Parcel result)
            {
                if (_send_request != null)
                    _send_request.Invoke(_instance, new object[] { result });
            }

            internal void Disconnect()
            {
                if (_online)
                _disconnect.Invoke(_instance, null);
                _online = false;
            }
        }

        
        public class RemoteException : Exception
        {
            public RemoteException()
            {
            }

            public RemoteException(string message)
            {
                this.Message = message;
            }

            public RemoteException(string message, int cause)
            {
                this.Message = message;
                this.Cause = cause;
            }

            public new string Message { get; set; }
            public int Cause { get; set; }
        }


        
        public class TizenEntityPresentation
        {
            


            public string Document;
            public string Template;

            public TizenEntityPresentation()
            {
            }

            public string ToJson()
            {
                string json_str = "{\"TizenEntityPresentation\":{";
                json_str += "\"Document\":";
                AppendToJson(ref json_str, Document);
        json_str += ",";        json_str += "\"Template\":";
                AppendToJson(ref json_str, Template);
                json_str += "}}";
                return json_str;
            }

            private static string JsonEscape(string str)
            {
                if (str == null) return "";
                var sb = new System.Text.StringBuilder(str.Length);
                foreach (char c in str)
                {
                    switch (c)
                    {
                        case '\\': sb.Append("\\\\"); break;
                        case '"': sb.Append("\\\""); break;
                        case '\b': sb.Append("\\b"); break;
                        case '\f': sb.Append("\\f"); break;
                        case '\n': sb.Append("\\n"); break;
                        case '\r': sb.Append("\\r"); break;
                        case '\t': sb.Append("\\t"); break;
                        default:
                            if (c < 0x20)
                                sb.Append("\\u").Append(((int)c).ToString("x4"));
                            else
                                sb.Append(c);
                            break;
                    }
                }
                return sb.ToString();
            }

            private static void AppendToJson(ref string json_str, object val)
            {
                if (val == null)
                {
                    json_str += "null";
                    return;
                }
                var type = val.GetType();
                if (type.IsEnum)
                {
                    json_str += ((int)val).ToString();
                }
                else if (val is bool b)
                {
                    json_str += b ? "true" : "false";
                }
                else if (val is string s)
                {
                    json_str += "\"" + JsonEscape(s) + "\"";
                }
                else if (val is float f)
                {
                    json_str += f.ToString(System.Globalization.CultureInfo.InvariantCulture);
                }
                else if (val is double d)
                {
                    json_str += d.ToString(System.Globalization.CultureInfo.InvariantCulture);
                }
                else if (val is sbyte || val is byte || val is short || val is ushort || val is int || val is uint || val is long || val is ulong)
                {
                    json_str += val.ToString();
                }
                else
                {
                    var method = type.GetMethod("ToJson");
                    if (method != null)
                    {
                        json_str += method.Invoke(val, null);
                    }
                    else if (val is System.Collections.IDictionary dict)
                    {
                        json_str += "{";
                        bool first = true;
                        foreach (System.Collections.DictionaryEntry entry in dict)
                        {
                            if (!first) json_str += ",";
                            string key_str = "";
                            AppendToJson(ref key_str, entry.Key);
                            if (!key_str.StartsWith("\""))
                            {
                                key_str = "\"" + key_str + "\"";
                            }
                            json_str += key_str + ":";
                            AppendToJson(ref json_str, entry.Value);
                            first = false;
                        }
                        json_str += "}";
                    }
                    else if (val is System.Collections.IEnumerable enumerable)
                    {
                        json_str += "[";
                        bool first = true;
                        foreach (var item in enumerable)
                        {
                            if (!first) json_str += ",";
                            AppendToJson(ref json_str, item);
                            first = false;
                        }
                        json_str += "]";
                    }
                    else
                    {
                        json_str += "null";
                    }
                }
            }

        }

        public class TizenEntityStatus
        {
            


            public bool Success;
            public string Reason;

            public TizenEntityStatus()
            {
            }

            public string ToJson()
            {
                string json_str = "{\"TizenEntityStatus\":{";
                json_str += "\"Success\":";
                AppendToJson(ref json_str, Success);
        json_str += ",";        json_str += "\"Reason\":";
                AppendToJson(ref json_str, Reason);
                json_str += "}}";
                return json_str;
            }

            private static string JsonEscape(string str)
            {
                if (str == null) return "";
                var sb = new System.Text.StringBuilder(str.Length);
                foreach (char c in str)
                {
                    switch (c)
                    {
                        case '\\': sb.Append("\\\\"); break;
                        case '"': sb.Append("\\\""); break;
                        case '\b': sb.Append("\\b"); break;
                        case '\f': sb.Append("\\f"); break;
                        case '\n': sb.Append("\\n"); break;
                        case '\r': sb.Append("\\r"); break;
                        case '\t': sb.Append("\\t"); break;
                        default:
                            if (c < 0x20)
                                sb.Append("\\u").Append(((int)c).ToString("x4"));
                            else
                                sb.Append(c);
                            break;
                    }
                }
                return sb.ToString();
            }

            private static void AppendToJson(ref string json_str, object val)
            {
                if (val == null)
                {
                    json_str += "null";
                    return;
                }
                var type = val.GetType();
                if (type.IsEnum)
                {
                    json_str += ((int)val).ToString();
                }
                else if (val is bool b)
                {
                    json_str += b ? "true" : "false";
                }
                else if (val is string s)
                {
                    json_str += "\"" + JsonEscape(s) + "\"";
                }
                else if (val is float f)
                {
                    json_str += f.ToString(System.Globalization.CultureInfo.InvariantCulture);
                }
                else if (val is double d)
                {
                    json_str += d.ToString(System.Globalization.CultureInfo.InvariantCulture);
                }
                else if (val is sbyte || val is byte || val is short || val is ushort || val is int || val is uint || val is long || val is ulong)
                {
                    json_str += val.ToString();
                }
                else
                {
                    var method = type.GetMethod("ToJson");
                    if (method != null)
                    {
                        json_str += method.Invoke(val, null);
                    }
                    else if (val is System.Collections.IDictionary dict)
                    {
                        json_str += "{";
                        bool first = true;
                        foreach (System.Collections.DictionaryEntry entry in dict)
                        {
                            if (!first) json_str += ",";
                            string key_str = "";
                            AppendToJson(ref key_str, entry.Key);
                            if (!key_str.StartsWith("\""))
                            {
                                key_str = "\"" + key_str + "\"";
                            }
                            json_str += key_str + ":";
                            AppendToJson(ref json_str, entry.Value);
                            first = false;
                        }
                        json_str += "}";
                    }
                    else if (val is System.Collections.IEnumerable enumerable)
                    {
                        json_str += "[";
                        bool first = true;
                        foreach (var item in enumerable)
                        {
                            if (!first) json_str += ",";
                            AppendToJson(ref json_str, item);
                            first = false;
                        }
                        json_str += "]";
                    }
                    else
                    {
                        json_str += "null";
                    }
                }
            }

        }

        public class TizenEntity
        {
            


            public string Id;
            public string Extra;

            public TizenEntity()
            {
            }

            public string ToJson()
            {
                string json_str = "{\"TizenEntity\":{";
                json_str += "\"Id\":";
                AppendToJson(ref json_str, Id);
        json_str += ",";        json_str += "\"Extra\":";
                AppendToJson(ref json_str, Extra);
                json_str += "}}";
                return json_str;
            }

            private static string JsonEscape(string str)
            {
                if (str == null) return "";
                var sb = new System.Text.StringBuilder(str.Length);
                foreach (char c in str)
                {
                    switch (c)
                    {
                        case '\\': sb.Append("\\\\"); break;
                        case '"': sb.Append("\\\""); break;
                        case '\b': sb.Append("\\b"); break;
                        case '\f': sb.Append("\\f"); break;
                        case '\n': sb.Append("\\n"); break;
                        case '\r': sb.Append("\\r"); break;
                        case '\t': sb.Append("\\t"); break;
                        default:
                            if (c < 0x20)
                                sb.Append("\\u").Append(((int)c).ToString("x4"));
                            else
                                sb.Append(c);
                            break;
                    }
                }
                return sb.ToString();
            }

            private static void AppendToJson(ref string json_str, object val)
            {
                if (val == null)
                {
                    json_str += "null";
                    return;
                }
                var type = val.GetType();
                if (type.IsEnum)
                {
                    json_str += ((int)val).ToString();
                }
                else if (val is bool b)
                {
                    json_str += b ? "true" : "false";
                }
                else if (val is string s)
                {
                    json_str += "\"" + JsonEscape(s) + "\"";
                }
                else if (val is float f)
                {
                    json_str += f.ToString(System.Globalization.CultureInfo.InvariantCulture);
                }
                else if (val is double d)
                {
                    json_str += d.ToString(System.Globalization.CultureInfo.InvariantCulture);
                }
                else if (val is sbyte || val is byte || val is short || val is ushort || val is int || val is uint || val is long || val is ulong)
                {
                    json_str += val.ToString();
                }
                else
                {
                    var method = type.GetMethod("ToJson");
                    if (method != null)
                    {
                        json_str += method.Invoke(val, null);
                    }
                    else if (val is System.Collections.IDictionary dict)
                    {
                        json_str += "{";
                        bool first = true;
                        foreach (System.Collections.DictionaryEntry entry in dict)
                        {
                            if (!first) json_str += ",";
                            string key_str = "";
                            AppendToJson(ref key_str, entry.Key);
                            if (!key_str.StartsWith("\""))
                            {
                                key_str = "\"" + key_str + "\"";
                            }
                            json_str += key_str + ":";
                            AppendToJson(ref json_str, entry.Value);
                            first = false;
                        }
                        json_str += "}";
                    }
                    else if (val is System.Collections.IEnumerable enumerable)
                    {
                        json_str += "[";
                        bool first = true;
                        foreach (var item in enumerable)
                        {
                            if (!first) json_str += ",";
                            AppendToJson(ref json_str, item);
                            first = false;
                        }
                        json_str += "]";
                    }
                    else
                    {
                        json_str += "null";
                    }
                }
            }

        }

        public class ScreenBounds
        {
            


            public double X;
            public double Y;
            public double Width;
            public double Height;

            public ScreenBounds()
            {
            }

            public string ToJson()
            {
                string json_str = "{\"ScreenBounds\":{";
                json_str += "\"X\":";
                AppendToJson(ref json_str, X);
        json_str += ",";        json_str += "\"Y\":";
                AppendToJson(ref json_str, Y);
        json_str += ",";        json_str += "\"Width\":";
                AppendToJson(ref json_str, Width);
        json_str += ",";        json_str += "\"Height\":";
                AppendToJson(ref json_str, Height);
                json_str += "}}";
                return json_str;
            }

            private static string JsonEscape(string str)
            {
                if (str == null) return "";
                var sb = new System.Text.StringBuilder(str.Length);
                foreach (char c in str)
                {
                    switch (c)
                    {
                        case '\\': sb.Append("\\\\"); break;
                        case '"': sb.Append("\\\""); break;
                        case '\b': sb.Append("\\b"); break;
                        case '\f': sb.Append("\\f"); break;
                        case '\n': sb.Append("\\n"); break;
                        case '\r': sb.Append("\\r"); break;
                        case '\t': sb.Append("\\t"); break;
                        default:
                            if (c < 0x20)
                                sb.Append("\\u").Append(((int)c).ToString("x4"));
                            else
                                sb.Append(c);
                            break;
                    }
                }
                return sb.ToString();
            }

            private static void AppendToJson(ref string json_str, object val)
            {
                if (val == null)
                {
                    json_str += "null";
                    return;
                }
                var type = val.GetType();
                if (type.IsEnum)
                {
                    json_str += ((int)val).ToString();
                }
                else if (val is bool b)
                {
                    json_str += b ? "true" : "false";
                }
                else if (val is string s)
                {
                    json_str += "\"" + JsonEscape(s) + "\"";
                }
                else if (val is float f)
                {
                    json_str += f.ToString(System.Globalization.CultureInfo.InvariantCulture);
                }
                else if (val is double d)
                {
                    json_str += d.ToString(System.Globalization.CultureInfo.InvariantCulture);
                }
                else if (val is sbyte || val is byte || val is short || val is ushort || val is int || val is uint || val is long || val is ulong)
                {
                    json_str += val.ToString();
                }
                else
                {
                    var method = type.GetMethod("ToJson");
                    if (method != null)
                    {
                        json_str += method.Invoke(val, null);
                    }
                    else if (val is System.Collections.IDictionary dict)
                    {
                        json_str += "{";
                        bool first = true;
                        foreach (System.Collections.DictionaryEntry entry in dict)
                        {
                            if (!first) json_str += ",";
                            string key_str = "";
                            AppendToJson(ref key_str, entry.Key);
                            if (!key_str.StartsWith("\""))
                            {
                                key_str = "\"" + key_str + "\"";
                            }
                            json_str += key_str + ":";
                            AppendToJson(ref json_str, entry.Value);
                            first = false;
                        }
                        json_str += "}";
                    }
                    else if (val is System.Collections.IEnumerable enumerable)
                    {
                        json_str += "[";
                        bool first = true;
                        foreach (var item in enumerable)
                        {
                            if (!first) json_str += ",";
                            AppendToJson(ref json_str, item);
                            first = false;
                        }
                        json_str += "]";
                    }
                    else
                    {
                        json_str += "null";
                    }
                }
            }

        }

        public class WindowBounds
        {
            


            public double X;
            public double Y;
            public double Width;
            public double Height;

            public WindowBounds()
            {
            }

            public string ToJson()
            {
                string json_str = "{\"WindowBounds\":{";
                json_str += "\"X\":";
                AppendToJson(ref json_str, X);
        json_str += ",";        json_str += "\"Y\":";
                AppendToJson(ref json_str, Y);
        json_str += ",";        json_str += "\"Width\":";
                AppendToJson(ref json_str, Width);
        json_str += ",";        json_str += "\"Height\":";
                AppendToJson(ref json_str, Height);
                json_str += "}}";
                return json_str;
            }

            private static string JsonEscape(string str)
            {
                if (str == null) return "";
                var sb = new System.Text.StringBuilder(str.Length);
                foreach (char c in str)
                {
                    switch (c)
                    {
                        case '\\': sb.Append("\\\\"); break;
                        case '"': sb.Append("\\\""); break;
                        case '\b': sb.Append("\\b"); break;
                        case '\f': sb.Append("\\f"); break;
                        case '\n': sb.Append("\\n"); break;
                        case '\r': sb.Append("\\r"); break;
                        case '\t': sb.Append("\\t"); break;
                        default:
                            if (c < 0x20)
                                sb.Append("\\u").Append(((int)c).ToString("x4"));
                            else
                                sb.Append(c);
                            break;
                    }
                }
                return sb.ToString();
            }

            private static void AppendToJson(ref string json_str, object val)
            {
                if (val == null)
                {
                    json_str += "null";
                    return;
                }
                var type = val.GetType();
                if (type.IsEnum)
                {
                    json_str += ((int)val).ToString();
                }
                else if (val is bool b)
                {
                    json_str += b ? "true" : "false";
                }
                else if (val is string s)
                {
                    json_str += "\"" + JsonEscape(s) + "\"";
                }
                else if (val is float f)
                {
                    json_str += f.ToString(System.Globalization.CultureInfo.InvariantCulture);
                }
                else if (val is double d)
                {
                    json_str += d.ToString(System.Globalization.CultureInfo.InvariantCulture);
                }
                else if (val is sbyte || val is byte || val is short || val is ushort || val is int || val is uint || val is long || val is ulong)
                {
                    json_str += val.ToString();
                }
                else
                {
                    var method = type.GetMethod("ToJson");
                    if (method != null)
                    {
                        json_str += method.Invoke(val, null);
                    }
                    else if (val is System.Collections.IDictionary dict)
                    {
                        json_str += "{";
                        bool first = true;
                        foreach (System.Collections.DictionaryEntry entry in dict)
                        {
                            if (!first) json_str += ",";
                            string key_str = "";
                            AppendToJson(ref key_str, entry.Key);
                            if (!key_str.StartsWith("\""))
                            {
                                key_str = "\"" + key_str + "\"";
                            }
                            json_str += key_str + ":";
                            AppendToJson(ref json_str, entry.Value);
                            first = false;
                        }
                        json_str += "}";
                    }
                    else if (val is System.Collections.IEnumerable enumerable)
                    {
                        json_str += "[";
                        bool first = true;
                        foreach (var item in enumerable)
                        {
                            if (!first) json_str += ",";
                            AppendToJson(ref json_str, item);
                            first = false;
                        }
                        json_str += "]";
                    }
                    else
                    {
                        json_str += "null";
                    }
                }
            }

        }

        public class Annotation
        {
            


            public string EntityId;
            public string EntityType;
            public string EntityInfo;

            public Annotation()
            {
            }

            public string ToJson()
            {
                string json_str = "{\"Annotation\":{";
                json_str += "\"EntityId\":";
                AppendToJson(ref json_str, EntityId);
        json_str += ",";        json_str += "\"EntityType\":";
                AppendToJson(ref json_str, EntityType);
        json_str += ",";        json_str += "\"EntityInfo\":";
                AppendToJson(ref json_str, EntityInfo);
                json_str += "}}";
                return json_str;
            }

            private static string JsonEscape(string str)
            {
                if (str == null) return "";
                var sb = new System.Text.StringBuilder(str.Length);
                foreach (char c in str)
                {
                    switch (c)
                    {
                        case '\\': sb.Append("\\\\"); break;
                        case '"': sb.Append("\\\""); break;
                        case '\b': sb.Append("\\b"); break;
                        case '\f': sb.Append("\\f"); break;
                        case '\n': sb.Append("\\n"); break;
                        case '\r': sb.Append("\\r"); break;
                        case '\t': sb.Append("\\t"); break;
                        default:
                            if (c < 0x20)
                                sb.Append("\\u").Append(((int)c).ToString("x4"));
                            else
                                sb.Append(c);
                            break;
                    }
                }
                return sb.ToString();
            }

            private static void AppendToJson(ref string json_str, object val)
            {
                if (val == null)
                {
                    json_str += "null";
                    return;
                }
                var type = val.GetType();
                if (type.IsEnum)
                {
                    json_str += ((int)val).ToString();
                }
                else if (val is bool b)
                {
                    json_str += b ? "true" : "false";
                }
                else if (val is string s)
                {
                    json_str += "\"" + JsonEscape(s) + "\"";
                }
                else if (val is float f)
                {
                    json_str += f.ToString(System.Globalization.CultureInfo.InvariantCulture);
                }
                else if (val is double d)
                {
                    json_str += d.ToString(System.Globalization.CultureInfo.InvariantCulture);
                }
                else if (val is sbyte || val is byte || val is short || val is ushort || val is int || val is uint || val is long || val is ulong)
                {
                    json_str += val.ToString();
                }
                else
                {
                    var method = type.GetMethod("ToJson");
                    if (method != null)
                    {
                        json_str += method.Invoke(val, null);
                    }
                    else if (val is System.Collections.IDictionary dict)
                    {
                        json_str += "{";
                        bool first = true;
                        foreach (System.Collections.DictionaryEntry entry in dict)
                        {
                            if (!first) json_str += ",";
                            string key_str = "";
                            AppendToJson(ref key_str, entry.Key);
                            if (!key_str.StartsWith("\""))
                            {
                                key_str = "\"" + key_str + "\"";
                            }
                            json_str += key_str + ":";
                            AppendToJson(ref json_str, entry.Value);
                            first = false;
                        }
                        json_str += "}";
                    }
                    else if (val is System.Collections.IEnumerable enumerable)
                    {
                        json_str += "[";
                        bool first = true;
                        foreach (var item in enumerable)
                        {
                            if (!first) json_str += ",";
                            AppendToJson(ref json_str, item);
                            first = false;
                        }
                        json_str += "]";
                    }
                    else
                    {
                        json_str += "null";
                    }
                }
            }

        }

        public class TizenEntityView: TizenEntity
        {
            


            public string Type;
            public string Description;
            public ScreenBounds ScreenBounds;
            public WindowBounds WindowBounds;
            public bool IsFocused;
            public bool IsEnabled;
            public Annotation Annotation;

            public TizenEntityView()
            {
            }

            public string ToJson()
            {
                string json_str = "{\"TizenEntityView\":{";
                json_str += "\"Id\":";
                AppendToJson(ref json_str, Id);
        json_str += ",";        json_str += "\"Extra\":";
                AppendToJson(ref json_str, Extra);
        json_str += ",";        json_str += "\"Type\":";
                AppendToJson(ref json_str, Type);
        json_str += ",";        json_str += "\"Description\":";
                AppendToJson(ref json_str, Description);
        json_str += ",";        json_str += "\"ScreenBounds\":";
                AppendToJson(ref json_str, ScreenBounds);
        json_str += ",";        json_str += "\"WindowBounds\":";
                AppendToJson(ref json_str, WindowBounds);
        json_str += ",";        json_str += "\"IsFocused\":";
                AppendToJson(ref json_str, IsFocused);
        json_str += ",";        json_str += "\"IsEnabled\":";
                AppendToJson(ref json_str, IsEnabled);
        json_str += ",";        json_str += "\"Annotation\":";
                AppendToJson(ref json_str, Annotation);
                json_str += "}}";
                return json_str;
            }

            private static string JsonEscape(string str)
            {
                if (str == null) return "";
                var sb = new System.Text.StringBuilder(str.Length);
                foreach (char c in str)
                {
                    switch (c)
                    {
                        case '\\': sb.Append("\\\\"); break;
                        case '"': sb.Append("\\\""); break;
                        case '\b': sb.Append("\\b"); break;
                        case '\f': sb.Append("\\f"); break;
                        case '\n': sb.Append("\\n"); break;
                        case '\r': sb.Append("\\r"); break;
                        case '\t': sb.Append("\\t"); break;
                        default:
                            if (c < 0x20)
                                sb.Append("\\u").Append(((int)c).ToString("x4"));
                            else
                                sb.Append(c);
                            break;
                    }
                }
                return sb.ToString();
            }

            private static void AppendToJson(ref string json_str, object val)
            {
                if (val == null)
                {
                    json_str += "null";
                    return;
                }
                var type = val.GetType();
                if (type.IsEnum)
                {
                    json_str += ((int)val).ToString();
                }
                else if (val is bool b)
                {
                    json_str += b ? "true" : "false";
                }
                else if (val is string s)
                {
                    json_str += "\"" + JsonEscape(s) + "\"";
                }
                else if (val is float f)
                {
                    json_str += f.ToString(System.Globalization.CultureInfo.InvariantCulture);
                }
                else if (val is double d)
                {
                    json_str += d.ToString(System.Globalization.CultureInfo.InvariantCulture);
                }
                else if (val is sbyte || val is byte || val is short || val is ushort || val is int || val is uint || val is long || val is ulong)
                {
                    json_str += val.ToString();
                }
                else
                {
                    var method = type.GetMethod("ToJson");
                    if (method != null)
                    {
                        json_str += method.Invoke(val, null);
                    }
                    else if (val is System.Collections.IDictionary dict)
                    {
                        json_str += "{";
                        bool first = true;
                        foreach (System.Collections.DictionaryEntry entry in dict)
                        {
                            if (!first) json_str += ",";
                            string key_str = "";
                            AppendToJson(ref key_str, entry.Key);
                            if (!key_str.StartsWith("\""))
                            {
                                key_str = "\"" + key_str + "\"";
                            }
                            json_str += key_str + ":";
                            AppendToJson(ref json_str, entry.Value);
                            first = false;
                        }
                        json_str += "}";
                    }
                    else if (val is System.Collections.IEnumerable enumerable)
                    {
                        json_str += "[";
                        bool first = true;
                        foreach (var item in enumerable)
                        {
                            if (!first) json_str += ",";
                            AppendToJson(ref json_str, item);
                            first = false;
                        }
                        json_str += "]";
                    }
                    else
                    {
                        json_str += "null";
                    }
                }
            }

        }



        namespace Stub
        {
            public class TizenActionView : StubBase
            {
                

                private List<ServiceBase> _services = new List<ServiceBase>();
                private Type _serviceType;
                private static readonly string _tidlVersion = "2.9.1";
                private Dictionary<MethodId, List<string>> _privilege_map = new Dictionary<MethodId, List<string>>();
                private static TizenActionView _instance;
                private bool _isListen = false;
                private SynchronizationContext _async_context = TizenSynchronizationContext.Current;

                public abstract class ServiceBase
                {
                    internal bool _is_app = true;
                    internal LocalExecution _lem;

                    /// <summary>
                    /// The client app ID
                    /// </summary>
                    public string Sender
                    {
                        get; internal set;
                    }

                    /// <summary>
                    /// The client instance ID
                    /// </summary>
                    public string Instance
                    {
                        get; internal set;
                    }

                    public Port Port
                    {
                        get;
                        internal set;
                    }

                    protected ServiceBase()
                    {

                    }

                    /// <summary>
                    /// Disconnects from the proxy app
                    /// </summary>
                    /// <exception cref="System.InvalidOperationException">
                    /// Thrown when an internal IO error occurrs.
                    /// </exception>
                    public void Disconnect()
                    {
                        if(_lem != null)
                        {
                            _lem.Disconnect();
                        }
                        else
                        {
                            Port?.Disconnect();
                            Port = null;
                        }
                    }

                    /// <summary>
                    /// This method will be called when the client is connected
                    /// </summary>
                    public abstract void OnCreate();

                    /// <summary>
                    /// This method will be called when the client is disconnected
                    /// </summary>
                    public abstract void OnTerminate();

                    public abstract TizenEntityStatus FindById(string id, out TizenEntityView v);

                    public abstract TizenEntityStatus GetAnnotatedViews(out List<TizenEntityView> views);

                    public abstract TizenEntityStatus GetFocusedView(out TizenEntityView v);

                    public abstract TizenEntityStatus ToPresentation(TizenEntityView view, out TizenEntityPresentation result);

                }

                
                internal class Unit
                {
                    internal int name;
                    internal int type;
                    internal Parcel parcel;
                    internal List<Action<Parcel>> cmds = new List<Action<Parcel>>();
                    internal Unit()
                    {
                    }

                    internal void Serialize(Parcel h)
                    {
                        h.WriteInt(name);
                        h.WriteInt(type);

                        var sizePos = h.GetDataSize();
                        h.Reserve(4);

                        foreach(var cb in cmds)
                        {
                            cb(h);
                        }

                        var curPos = h.GetDataSize();
                        var size = curPos - sizePos - 4;
                        h.SetDataSize(sizePos);
                        h.WriteInt((int)size);
                        h.SetDataSize(curPos);
                    }

                    internal void Deserialize(Parcel h)
                    {
                        name = h.ReadInt();
                        type = h.ReadInt();
                        var size = h.ReadArrayCount();
                        if (size == 0)
                            return;

                        var startPos = h.GetReader();
                        parcel = new Parcel(h, startPos, (uint)size);
                        parcel.Reserve((uint)size);
                        h.SetReader(startPos + (uint)size);
                    }
                }

                internal class UnitMap
                {
                    internal Dictionary<int, Unit> map;
                    internal UnitMap()
                    {
                        map = new Dictionary<int, Unit>();
                    }

                    internal void Serialize(Parcel parcel)
                    {
                        parcel.WriteArrayCount(map.Count & int.MaxValue);
                        foreach (Unit unit in map.Values)
                        {
                            unit.Serialize(parcel);
                        }
                    }

                    internal void Deserialize(Parcel parcel)
                    {
                        int size = parcel.ReadArrayCount();
                        parcel.Pin();

                        for (int i = 0; i < size; i++)
                        {
                            Unit unit = new Unit();
                            unit.Deserialize(parcel);

                            map[unit.name] = unit;
                        }
                    }

                    internal bool ContainsName(int name)
                    {
                        return map.ContainsKey(name);
                    }

                    
                    internal void Read(int name, out List<TizenEntityView> value)
                    {
                        value = new List<TizenEntityView>();
                        if (map.ContainsKey(name) == false)
                        {
                            Tizen.Log.Error("RPC_PORT", "Not exist key " + name);
                            return;
                        }

                        Unit unit = map[name];
                        if (unit.type != -1094159920 /*array_TizenEntityView*/)
                        {
                            Tizen.Log.Error("RPC_PORT", "type is not array_TizenEntityView : " + unit.type);
                            return;
                        }
                        TizenActionView.Deserialize(unit.parcel, value);
                    }

                    internal void Write(int name, List<TizenEntityView> value)
                    {
                        Unit unit = new Unit();
                        unit.name = name;
                        unit.type = -1094159920; /*array_TizenEntityView*/
                        unit.cmds.Add((parcel) =>
                        {
                            TizenActionView.Serialize(parcel, value);
                        });

                        map[name] = unit;
                    }

                    internal void Read(int name, out TizenEntityView value)
                    {
                        value = new TizenEntityView();
                        if (map.ContainsKey(name) == false)
                        {
                            Tizen.Log.Error("RPC_PORT", "Not exist key " + name);
                            return;
                        }

                        Unit unit = map[name];
                        if (unit.type != -1014526171 /*TizenEntity::TizenEntityView*/)
                        {
                            Tizen.Log.Error("RPC_PORT", "type is not TizenEntity::TizenEntityView : " + unit.type);
                            return;
                        }
                        TizenActionView.Deserialize(unit.parcel, value);
                    }

                    internal void Write(int name, TizenEntityView value)
                    {
                        Unit unit = new Unit();
                        unit.name = name;
                        unit.type = -1014526171; /*TizenEntity::TizenEntityView*/
                        unit.cmds.Add((parcel) =>
                        {
                            TizenActionView.Serialize(parcel, value);
                        });

                        map[name] = unit;
                    }

                    internal void Read(int name, out TizenEntityPresentation value)
                    {
                        value = new TizenEntityPresentation();
                        if (map.ContainsKey(name) == false)
                        {
                            Tizen.Log.Error("RPC_PORT", "Not exist key " + name);
                            return;
                        }

                        Unit unit = map[name];
                        if (unit.type != 1161731883 /*TizenEntityPresentation*/)
                        {
                            Tizen.Log.Error("RPC_PORT", "type is not TizenEntityPresentation : " + unit.type);
                            return;
                        }
                        TizenActionView.Deserialize(unit.parcel, value);
                    }

                    internal void Write(int name, TizenEntityPresentation value)
                    {
                        Unit unit = new Unit();
                        unit.name = name;
                        unit.type = 1161731883; /*TizenEntityPresentation*/
                        unit.cmds.Add((parcel) =>
                        {
                            TizenActionView.Serialize(parcel, value);
                        });

                        map[name] = unit;
                    }

                    internal void Read(int name, out TizenEntityStatus value)
                    {
                        value = new TizenEntityStatus();
                        if (map.ContainsKey(name) == false)
                        {
                            Tizen.Log.Error("RPC_PORT", "Not exist key " + name);
                            return;
                        }

                        Unit unit = map[name];
                        if (unit.type != -1652879165 /*TizenEntityStatus*/)
                        {
                            Tizen.Log.Error("RPC_PORT", "type is not TizenEntityStatus : " + unit.type);
                            return;
                        }
                        TizenActionView.Deserialize(unit.parcel, value);
                    }

                    internal void Write(int name, TizenEntityStatus value)
                    {
                        Unit unit = new Unit();
                        unit.name = name;
                        unit.type = -1652879165; /*TizenEntityStatus*/
                        unit.cmds.Add((parcel) =>
                        {
                            TizenActionView.Serialize(parcel, value);
                        });

                        map[name] = unit;
                    }

                    internal void Read(int name, out string value)
                    {
                        value = new string("");
                        if (map.ContainsKey(name) == false)
                        {
                            Tizen.Log.Error("RPC_PORT", "Not exist key " + name);
                            return;
                        }

                        Unit unit = map[name];
                        if (unit.type != -891985903 /*string*/)
                        {
                            Tizen.Log.Error("RPC_PORT", "type is not string : " + unit.type);
                            return;
                        }
                        value = unit.parcel.ReadString();
                    }

                    internal void Write(int name, string value)
                    {
                        Unit unit = new Unit();
                        unit.name = name;
                        unit.type = -891985903; /*string*/
                        unit.cmds.Add((parcel) =>
                        {
                            parcel.WriteString(value);
                        });

                        map[name] = unit;
                    }

                    internal void Read(int name, out int value)
                    {
                        value = new int();
                        if (map.ContainsKey(name) == false)
                        {
                            Tizen.Log.Error("RPC_PORT", "Not exist key " + name);
                            return;
                        }

                        Unit unit = map[name];
                        if (unit.type != 104431 /*int*/)
                        {
                            Tizen.Log.Error("RPC_PORT", "type is not int : " + unit.type);
                            return;
                        }
                        value = unit.parcel.ReadInt();
                    }

                    internal void Write(int name, int value)
                    {
                        Unit unit = new Unit();
                        unit.name = name;
                        unit.type = 104431; /*int*/
                        unit.cmds.Add((parcel) =>
                        {
                            parcel.WriteInt(value);
                        });

                        map[name] = unit;
                    }

                    internal void Read(int name, out bool value)
                    {
                        value = new bool();
                        if (map.ContainsKey(name) == false)
                        {
                            Tizen.Log.Error("RPC_PORT", "Not exist key " + name);
                            return;
                        }

                        Unit unit = map[name];
                        if (unit.type != 3029738 /*bool*/)
                        {
                            Tizen.Log.Error("RPC_PORT", "type is not bool : " + unit.type);
                            return;
                        }
                        value = unit.parcel.ReadBool();
                    }

                    internal void Write(int name, bool value)
                    {
                        Unit unit = new Unit();
                        unit.name = name;
                        unit.type = 3029738; /*bool*/
                        unit.cmds.Add((parcel) =>
                        {
                            parcel.WriteBool(value);
                        });

                        map[name] = unit;
                    }

                    internal void Read(int name, out CallbackBase value)
                    {
                        value = new CallbackBase(1, false);
                        if (map.ContainsKey(name) == false)
                        {
                            Tizen.Log.Error("RPC_PORT", "Not exist key " + name);
                            return;
                        }

                        Unit unit = map[name];
                        if (unit.type != 819322245 /*delegate*/)
                        {
                            Tizen.Log.Error("RPC_PORT", "type is not delegate : " + unit.type);
                            return;
                        }
                        CallbackBase.Deserialize(unit.parcel, value);
                    }

                    internal void Write(int name, CallbackBase value)
                    {
                        Unit unit = new Unit();
                        unit.name = name;
                        unit.type = 819322245; /*delegate*/
                        unit.cmds.Add((parcel) =>
                        {
                            CallbackBase.Serialize(parcel, value);
                        });

                        map[name] = unit;
                    }

                    internal void Read(int name, out RemoteException value)
                    {
                        value = new RemoteException();
                        if (map.ContainsKey(name) == false)
                        {
                            Tizen.Log.Error("RPC_PORT", "Not exist key " + name);
                            return;
                        }

                        Unit unit = map[name];
                        if (unit.type != -1223777386 /*remote_exception*/)
                        {
                            Tizen.Log.Error("RPC_PORT", "type is not remote_exception : " + unit.type);
                            return;
                        }
                        TizenActionView.Deserialize(unit.parcel, value);
                    }

                    internal void Write(int name, RemoteException value)
                    {
                        Unit unit = new Unit();
                        unit.name = name;
                        unit.type = -1223777386; /*remote_exception*/
                        unit.cmds.Add((parcel) =>
                        {
                            TizenActionView.Serialize(parcel, value);
                        });

                        map[name] = unit;
                    }

                }

                
                public class CallbackBase
                {
                    internal int Id;
                    internal int SeqId;
                    internal bool Once;
                    private static volatile int _seqNum = 0;

                    public string Tag
                    {
                        get
                        {
                            return Id.ToString() + "::" + SeqId.ToString();
                        }
                    }

                    public CallbackBase(int delegateId, bool once)
                    {
                        Id = delegateId;
                        SeqId = _seqNum++;
                        Once = once;
                    }

                    internal virtual void OnReceivedEvent(UnitMap map) {}

                    internal static void Serialize(Parcel h, CallbackBase param)
                    {
                        h.WriteInt(param.Id);
                        h.WriteInt(param.SeqId);
                        h.WriteBool(param.Once);
                    }

                    internal static void Deserialize(Parcel h, CallbackBase param)
                    {
                        param.Id = h.ReadInt();
                        param.SeqId = h.ReadInt();
                        param.Once = h.ReadBool();
                    }
                }



                
                
                private enum MethodId : int
                {
                    __Result = 0,
                    __Callback = 1,
                    FindById = 2,
                    GetAnnotatedViews = 3,
                    GetFocusedView = 4,
                    ToPresentation = 5,
                }

                
                private static void Serialize(Parcel h, TizenEntityPresentation param)
                {
                    h.WriteString(param.Document);
                    h.WriteString(param.Template);
                }

                private static void Deserialize(Parcel h, TizenEntityPresentation param)
                {
                    var Document = h.ReadString();
                    param.Document = Document;
                    var Template = h.ReadString();
                    param.Template = Template;
                }

                private static void Serialize(Parcel h, TizenEntityStatus param)
                {
                    h.WriteBool(param.Success);
                    h.WriteString(param.Reason);
                }

                private static void Deserialize(Parcel h, TizenEntityStatus param)
                {
                    var Success = h.ReadBool();
                    param.Success = Success;
                    var Reason = h.ReadString();
                    param.Reason = Reason;
                }

                private static void Serialize(Parcel h, TizenEntity param)
                {
                    h.WriteString(param.Id);
                    h.WriteString(param.Extra);
                }

                private static void Deserialize(Parcel h, TizenEntity param)
                {
                    var Id = h.ReadString();
                    param.Id = Id;
                    var Extra = h.ReadString();
                    param.Extra = Extra;
                }

                private static void Serialize(Parcel h, ScreenBounds param)
                {
                    h.WriteDouble(param.X);
                    h.WriteDouble(param.Y);
                    h.WriteDouble(param.Width);
                    h.WriteDouble(param.Height);
                }

                private static void Deserialize(Parcel h, ScreenBounds param)
                {
                    var X = h.ReadDouble();
                    param.X = X;
                    var Y = h.ReadDouble();
                    param.Y = Y;
                    var Width = h.ReadDouble();
                    param.Width = Width;
                    var Height = h.ReadDouble();
                    param.Height = Height;
                }

                private static void Serialize(Parcel h, WindowBounds param)
                {
                    h.WriteDouble(param.X);
                    h.WriteDouble(param.Y);
                    h.WriteDouble(param.Width);
                    h.WriteDouble(param.Height);
                }

                private static void Deserialize(Parcel h, WindowBounds param)
                {
                    var X = h.ReadDouble();
                    param.X = X;
                    var Y = h.ReadDouble();
                    param.Y = Y;
                    var Width = h.ReadDouble();
                    param.Width = Width;
                    var Height = h.ReadDouble();
                    param.Height = Height;
                }

                private static void Serialize(Parcel h, Annotation param)
                {
                    h.WriteString(param.EntityId);
                    h.WriteString(param.EntityType);
                    h.WriteString(param.EntityInfo);
                }

                private static void Deserialize(Parcel h, Annotation param)
                {
                    var EntityId = h.ReadString();
                    param.EntityId = EntityId;
                    var EntityType = h.ReadString();
                    param.EntityType = EntityType;
                    var EntityInfo = h.ReadString();
                    param.EntityInfo = EntityInfo;
                }

                private static void Serialize(Parcel h, TizenEntityView param)
                {
                    Serialize(h, (TizenEntity)param);
                    h.WriteString(param.Type);
                    h.WriteString(param.Description);
                    Serialize(h, param.ScreenBounds);
                    Serialize(h, param.WindowBounds);
                    h.WriteBool(param.IsFocused);
                    h.WriteBool(param.IsEnabled);
                    Serialize(h, param.Annotation);
                }

                private static void Deserialize(Parcel h, TizenEntityView param)
                {
                    Deserialize(h, (TizenEntity)param);
                    var Type = h.ReadString();
                    param.Type = Type;
                    var Description = h.ReadString();
                    param.Description = Description;
                    param.ScreenBounds = new ScreenBounds();
                    Deserialize(h, param.ScreenBounds);
                    param.WindowBounds = new WindowBounds();
                    Deserialize(h, param.WindowBounds);
                    var IsFocused = h.ReadBool();
                    param.IsFocused = IsFocused;
                    var IsEnabled = h.ReadBool();
                    param.IsEnabled = IsEnabled;
                    param.Annotation = new Annotation();
                    Deserialize(h, param.Annotation);
                }

                
                private static void Serialize(Parcel h, List<TizenEntityView> param)
                {
                    h.WriteArrayCount(param.Count);
                    foreach (var i in param)
                    {
                        Serialize(h, i);
                    }
                }

                private static void Deserialize(Parcel h, List<TizenEntityView> param)
                {
                    int l = h.ReadArrayCount();
                    for (int i = 0; i < l; i++)
                    {
                        var k = new TizenEntityView();
                        Deserialize(h, k);
                        param.Add(k);
                    }
                }

                
                private static void Serialize(Parcel h, RemoteException param)
                {
                    h.WriteInt(param.Cause);
                    h.WriteString(param.Message);
                }

                private static void Deserialize(Parcel h, RemoteException param)
                {
                    param.Cause = h.ReadInt();
                    param.Message = h.ReadString();
                }


                private bool CheckPrivilege(MethodId id, ServiceBase b)
                {
                    if (_privilege_map.ContainsKey(id) == false)
                        return true;

                    var privileges = _privilege_map[id];
                    bool has;
                    foreach (var item in privileges)
                    {
#if TIZEN_RPCPORT_HAS_PRIVILEGE_LOCAL
                        // has = HasPrivilegeLocal(b.Sender, item);
                        // Disabled for compatibility with runtimes that omit StubBase.HasPrivilegeLocal.
                        has = false;
#else
                        // Older released Tizen.NET packages do not expose the
                        // UDS-specific API. Deny rather than weakening checks.
                        has = false;
#endif
                        if (has == false) {
                            Tizen.Log.Error("RPC_PORT", "Permission denied. " + b.Sender + " : " + item);
                            return false;
                        }
                    }

                    return true;
                }

                protected override bool OnReceivedEvent(string sender, string instance, Port port)
                {
                    Parcel p;

                    try
                    {
                        p = new Parcel(port);
                    }
                    catch (InvalidIOException)
                    {
                        return false;
                    }

                    return OnReceivedEvent(instance, port, p);
                }

                internal void OnLemReceivedEvent(string instance, Parcel p)
                {
                    if (Thread.CurrentThread.ManagedThreadId != 1)
                    {
                        _async_context.Post((data) =>
                        {
                            ((TizenActionView)data).OnReceivedEvent(instance, null, p);
                        }, this);
                    }
                    else
                    {
                        OnReceivedEvent(instance, null, p);
                    }
                }

                internal  bool OnReceivedEvent(string instance, Port port, Parcel p)
                {
                    try
                    {
                        ServiceBase b = null;

                        foreach (var i in  _services)
                        {
                            if (i.Instance.Equals(instance))
                            {
                                b = i;
                                break;
                            }
                        }

                        if (b == null)
                        {
                            return false;
                        }

                        Port cb_port;
                        if (b._lem != null)
                            cb_port = null;
                        else
                            cb_port = GetPort(Port.Type.Callback, instance);

                        var result = new Parcel();

                        int cmd;
                        UnitMap map = new UnitMap();
                        map.Deserialize(p);

                        map.Read(1355467489 /*[METHOD]*/, out cmd);

                        switch ((MethodId)cmd)
                        {
                            case MethodId.FindById:
                            {
                                map.Read(3355 /*id*/, out string param1);
                                UnitMap result_map = new UnitMap();
                                if (b._is_app && CheckPrivilege((MethodId)cmd, b) == false)
                                {
                                    RemoteException ex = new RemoteException("Permission denied", (int)Tizen.Internals.Errors.ErrorCode.PermissionDenied);
                                    result_map.Write(-1571313492 /*[REMOTE_EXCEPTION]*/, ex);
                                } else {
                                    try
                                    {
                                        var retVal = b.FindById(param1, out TizenEntityView param2);
                                        result_map.Write(1497479973 /*[RESULT]*/, retVal);
                                        result_map.Write(118 /*v*/, param2);
                                    } catch (RemoteException ex)
                                    {
                                        result_map.Write(-1571313492 /*[REMOTE_EXCEPTION]*/, ex);
                                    }
                                }

                                ParcelHeader header = p.GetHeader();
                                ParcelHeader resultHeader = result.GetHeader();
                                resultHeader.SetTag(_tidlVersion + ":2:13");
                                resultHeader.SetSequenceNumber(header.GetSequenceNumber());
                                int ret_cmd = (int)MethodId.__Result;
                                result_map.Write(1355467489 /*[METHOD]*/, ret_cmd);
                                result_map.Serialize(result);

                                if (b._lem != null)
                                    b._lem.SendResult(result);
                                else
                                    result.Send(port);
                                break;
                            }
                            case MethodId.GetAnnotatedViews:
                            {
                                UnitMap result_map = new UnitMap();
                                if (b._is_app && CheckPrivilege((MethodId)cmd, b) == false)
                                {
                                    RemoteException ex = new RemoteException("Permission denied", (int)Tizen.Internals.Errors.ErrorCode.PermissionDenied);
                                    result_map.Write(-1571313492 /*[REMOTE_EXCEPTION]*/, ex);
                                } else {
                                    try
                                    {
                                        var retVal = b.GetAnnotatedViews(out List<TizenEntityView> param1);
                                        result_map.Write(1497479973 /*[RESULT]*/, retVal);
                                        result_map.Write(112204398 /*views*/, param1);
                                    } catch (RemoteException ex)
                                    {
                                        result_map.Write(-1571313492 /*[REMOTE_EXCEPTION]*/, ex);
                                    }
                                }

                                ParcelHeader header = p.GetHeader();
                                ParcelHeader resultHeader = result.GetHeader();
                                resultHeader.SetTag(_tidlVersion + ":2:13");
                                resultHeader.SetSequenceNumber(header.GetSequenceNumber());
                                int ret_cmd = (int)MethodId.__Result;
                                result_map.Write(1355467489 /*[METHOD]*/, ret_cmd);
                                result_map.Serialize(result);

                                if (b._lem != null)
                                    b._lem.SendResult(result);
                                else
                                    result.Send(port);
                                break;
                            }
                            case MethodId.GetFocusedView:
                            {
                                UnitMap result_map = new UnitMap();
                                if (b._is_app && CheckPrivilege((MethodId)cmd, b) == false)
                                {
                                    RemoteException ex = new RemoteException("Permission denied", (int)Tizen.Internals.Errors.ErrorCode.PermissionDenied);
                                    result_map.Write(-1571313492 /*[REMOTE_EXCEPTION]*/, ex);
                                } else {
                                    try
                                    {
                                        var retVal = b.GetFocusedView(out TizenEntityView param1);
                                        result_map.Write(1497479973 /*[RESULT]*/, retVal);
                                        result_map.Write(118 /*v*/, param1);
                                    } catch (RemoteException ex)
                                    {
                                        result_map.Write(-1571313492 /*[REMOTE_EXCEPTION]*/, ex);
                                    }
                                }

                                ParcelHeader header = p.GetHeader();
                                ParcelHeader resultHeader = result.GetHeader();
                                resultHeader.SetTag(_tidlVersion + ":2:13");
                                resultHeader.SetSequenceNumber(header.GetSequenceNumber());
                                int ret_cmd = (int)MethodId.__Result;
                                result_map.Write(1355467489 /*[METHOD]*/, ret_cmd);
                                result_map.Serialize(result);

                                if (b._lem != null)
                                    b._lem.SendResult(result);
                                else
                                    result.Send(port);
                                break;
                            }
                            case MethodId.ToPresentation:
                            {
                                map.Read(3619493 /*view*/, out TizenEntityView param1);
                                UnitMap result_map = new UnitMap();
                                if (b._is_app && CheckPrivilege((MethodId)cmd, b) == false)
                                {
                                    RemoteException ex = new RemoteException("Permission denied", (int)Tizen.Internals.Errors.ErrorCode.PermissionDenied);
                                    result_map.Write(-1571313492 /*[REMOTE_EXCEPTION]*/, ex);
                                } else {
                                    try
                                    {
                                        var retVal = b.ToPresentation(param1, out TizenEntityPresentation param2);
                                        result_map.Write(1497479973 /*[RESULT]*/, retVal);
                                        result_map.Write(-934426595 /*result*/, param2);
                                    } catch (RemoteException ex)
                                    {
                                        result_map.Write(-1571313492 /*[REMOTE_EXCEPTION]*/, ex);
                                    }
                                }

                                ParcelHeader header = p.GetHeader();
                                ParcelHeader resultHeader = result.GetHeader();
                                resultHeader.SetTag(_tidlVersion + ":2:13");
                                resultHeader.SetSequenceNumber(header.GetSequenceNumber());
                                int ret_cmd = (int)MethodId.__Result;
                                result_map.Write(1355467489 /*[METHOD]*/, ret_cmd);
                                result_map.Serialize(result);

                                if (b._lem != null)
                                    b._lem.SendResult(result);
                                else
                                    result.Send(port);
                                break;
                            }

                            default:
                                return false;
                        }

                        return true;
                    }
                    catch (InvalidIOException)
                    {
                        return false;
                    }
                    finally
                    {
                        p.Dispose();
                    }
                }

                protected override void OnConnectedEvent(string sender, string instance)
                {
                    ServiceBase s = Activator.CreateInstance(_serviceType) as ServiceBase;
                    s.Sender = sender;
                    s.Instance = instance;
                    s.Port = GetPort(Port.Type.Callback, instance);
                    _services.Add(s);
                    s.OnCreate();
                }

                internal void OnLemConnectedEvent(object proxy_instance, string sender, string instance)
                {
                    ServiceBase s = Activator.CreateInstance(_serviceType) as ServiceBase;
                    s.Sender = sender;
                    s.Instance = instance;
                    s._lem = new LocalExecution(proxy_instance);
                    _services.Add(s);
                    if (Thread.CurrentThread.ManagedThreadId != 1)
                    {
                        _async_context.Post((data) =>
                        {
                            ((ServiceBase)data).OnCreate();
                        }, s);
                    }
                    else
                    {
                        s.OnCreate();
                    }
                }

                protected override void OnDisconnectedEvent(string sender, string instance)
                {
                    foreach (var i in _services)
                    {
                        if (i.Instance.Equals(instance))
                        {
                            if (i._lem != null)
                                i._lem._online = false;

                            i.OnTerminate();
                            _services.Remove(i);
                            break;
                        }
                    }
                }

                internal void OnLemDisconnectedEvent(string sender, string instance)
                {
                    if (Thread.CurrentThread.ManagedThreadId != 1)
                    {
                        _async_context.Post((data) =>
                        {
                            ((TizenActionView)data).OnDisconnectedEvent(sender, instance);
                        }, this);
                    }
                    else
                    {
                        OnDisconnectedEvent(sender, instance);
                    }
                }

                internal static TizenActionView GetInstance()
                {
                    return _instance;
                }

                internal bool GetListenStatus()
                {
                    return _isListen;
                }

                public TizenActionView() : base("TizenActionView")
                {
                    _instance = this;


                }

                /// <summary>
                /// Listens to client apps
                /// </summary>
                /// <param name="serviceType">The type object for making service instances</param>
                /// <exception cref="InvalidIOException">
                /// Thrown when internal I/O error happen.
                /// </exception>
                /// <exception cref="ArgumentException">
                /// Thrown when serviceType is invalid.
                /// </exception>
                public void Listen(Type serviceType)
                {
                    if (!typeof(ServiceBase).IsAssignableFrom(serviceType))
                        throw new ArgumentException("Invalid type");
                    _serviceType = serviceType;
                    Listen();
                    _isListen = true;
                }

                /// <summary>
                /// Gets service objects which are connected
                /// </summary>
                /// <returns>The enumerable service objects which are connected</returns>
                public IEnumerable<ServiceBase> GetServices()
                {
                    return _services;
                }


                protected override void OnTerminatedEvent()
                {
                    foreach (var i in _services)
                    {
                        if (i._lem != null)
                        i._lem._online = false;
                        i.OnTerminate();
                    }
                }

            }
        }
    }
}

